### ISSUE TITLE
JUnit XML output

### ISSUE THREAD

**Issue by drug007** [atilaneves/unit-threaded#10]
It would be very nice to have opportunity to use unit-threaded with Jenkins/Hudson.

**Comment by atilaneves** [comment]
That'd be nice but I don't use Jenkins or Hudson and don't know what the format is like.

**Comment by joakim-brannstrom** [comment]
A little bit of information. Here is an example from google test.

[GoogleTest XML/JUnit](https://github.com/google/googletest/blob/master/googletest/test/gtest_xml_output_unittest.py)

**Comment by atilaneves** [comment]
PRs welcome.
