### ISSUE TITLE
run tests based on location

### ISSUE THREAD

**Issue by MartinNowak** [atilaneves/unit-threaded#101]
A very nice feat of rspec is `rspec ./run/that/damn/test:56`, which will only select the unittest block at that location. Nicely integratable into IDEs, a.k.a. run test at cursor.

Not too sure how to pull this off.
DMD already has the starting line number in the unittest name mangling, e.g. `_D6review28__unittest_test_review_d_4_0FZv` (`void review.__unittest_test_review_d_4_0()`).
Selecting the test that starts before or at the specified line would be a close enough behavior.

Only when the selected line is not a unittest, this could accidentally still run the preceding one.

Also the beginning line of a test makes for a nicer default unittest name, cause I can find it without counting through the file, i.e. `mymod.unittest_123` instead of `mymod.unittest2`.

**Comment by atilaneves** [comment]
unit-threaded can run based on name already so the editor could backtrack until it finds a `@("...")` UDA. Alternatively, unit-threaded could store the line number of the unittest but without trying I don't know how hard that would be.

Storing the line number would also be necessary to change the default unittest name to include the line number. I've never used or cared about the defaults - they exist to need _a_ name. The recommended way is to name all of them.

**Comment by atilaneves** [comment]
If you have a `unittest` block in a module called `pkg1.pkg2.mod1`, and it happens to be on the 1st column of the 13th line of that module, then you'll be able to pass `pkg1.pkg2.mod1.unittest_L13_C1` and run it.
