### ISSUE TITLE
Support for randomized testing

### ISSUE THREAD

**Issue by Dechcaudron** [atilaneves/unit-threaded#102]
Similar to when using `@Values(...)`, but so that each test run gets a seed and generates test-dependent data from it. When a test fails, it would also report the seed used to run it. I can imagine different approaches, but are you open to the idea? The interface would be something like

```D
@Randomized
unittest
{
    uint seed = getSeed();
    // Do test stuff with your seed
}
```

**Comment by atilaneves** [comment]
Have you looked at unit-theaded's support for property-based testing?

**Comment by MartinNowak** [comment]
Check https://github.com/MartinNowak/qcheck for random testing, based on Haskell's excellent [QuickCheck](https://wiki.haskell.org/Introduction_to_QuickCheck1).
It can generate arbitrary data for you with very customizable behavior. Unfortunately not too well documented atm.
Andrei suggested to me that I prop it up for std.random inclusion, but it's too low a priority for me to spent time on. I'd be glad if someone would adopt it.
It's a particular helpful tool to test numeric code and algorithms, as it relentlessly finds corner cases.

**Comment by Dechcaudron** [comment]
@atilaneves: Just saw it, I apologize for the noise.

@MartinNowak: looking good, will use it next time I need to test a numeric algorithm. I'll open an issue in that repo should I have any doubts about it.
