### ISSUE TITLE
Package version number

### ISSUE THREAD

**Issue by russel** [atilaneves/unit-threaded#105]
Having the version number explicitly in the Meson build is clearly the wrong thing to do per se for this project. However in order to build the shared objects on Linux the version number and soname are required. It seems though that the unit-threaded version number as per the Dub repository is nowhere in the source repository, it is just the Git tag in GitHub.

Meson builds, and indeed other builds, make the assumption that the build can happen outside a repository whereas the current system appears to be driven totally within GitHub.

This is really a question rather than an issue, to try and decide what is the best way of getting a reasonable version and soname for the Meson build. It is non-standard to assume build in a git repository, but that is looking like the only way forward.

**Comment by atilaneves** [comment]
I guess I could write a script that tags the repo and adds the tag to a file that meson could use.

What would be the point of building unit-threaded as a shared library? Nearly everything it does is at compile-time anyway.

**Comment by russel** [comment]
"Nearly everything" is the problem? If any of the code is required at runtime, then the shared library has purpose. If though all of the unit-threaded code is compile-time only with no runtime, then it is just a question of installing the module source, no library of any sort needed.

**Comment by atilaneves** [comment]
I'll just do this manually.
