### ISSUE TITLE
Test runner hangs after completing

### ISSUE THREAD

**Issue by Abscissa** [atilaneves/unit-threaded#107]
After the test runner finishes (even if it doesn't find any tests to run), it doesn't exit, it just sits there and I have to Ctrl-C.

(And if the last text it output was red or green, it leaves my terminal outputting everything from then on it that color.)

**Comment by atilaneves** [comment]
Does your project depend on vibe.d?

**Comment by Abscissa** [comment]
On February 5, 2018 5:45:53 AM EST, Atila Neves <notifications@github.com> wrote:
>Does your project depend on vibe.d?

Yes

**Comment by atilaneves** [comment]
https://github.com/vibe-d/vibe.d/issues/1657
https://github.com/atilaneves/unit-threaded/issues/78

Try using the `-s` command-line option or enabling `versions "unitUnthreaded"`. It's really a vibe.d issue.

**Comment by ghost91-** [comment]
I'm having the same problem. Using the `-s` commandline flag does not fix it.

**Comment by Abscissa** [comment]
I can confirm @ghost91- 's experience:

- v0.7.38 hangs regardless of whether or not I use `-s`.
- v0.7.37 does NOT hang regardless of whether or not I use `-s`.

**Comment by atilaneves** [comment]
And using the `unitUnthreaded` version?

**Comment by ghost91-** [comment]
I can confirm that using version `unitUnthreaded` does fix the problem. The question remains why the problem is only introduced with v0.7.38.

**Comment by atilaneves** [comment]
I changed a few thread things to sort out some other issues. I'll look into this, but the truth is that vibe is very particular about threads and in all likelihood there's nothing much I can do (famous last words).
