### ISSUE TITLE
Wrong symbol resolution

### ISSUE THREAD

**Issue by drug007** [atilaneves/unit-threaded#11]
foo.d:

```
module foo;

struct foo
{
}
```

test.d:

```
import foo;
import unit_threaded.runner;

int main(string[] args)
{
return args.runTests!(foo);
}
```

building fails because foo.foo is got as package.module instead of module.structure. I make bindings to GSL and there is a file `gsl_rng` that has `struct gsl_rng` and that prevents tests from building.

**Comment by atilaneves** [comment]
A workaround for now is:

    import bar = foo;
    import unit_threaded.runner;

    int main(string[] args) {
        return args.runTests!(bar);
    }

**Comment by drug007** [comment]
Indeed. Thanks!
