### ISSUE TITLE
Property testing strings produces invalid unicode strings

### ISSUE THREAD

**Issue by dhasenan** [atilaneves/unit-threaded#112]
I'd expect valid unicode strings by default, potentially limited to 7-bit ASCII.

Test case:

```D
import unit_threaded;
import std.utf;

@("Check for unicode strings")
unittest
{
    bool tester(string v)
    {
        validate(v);
        return true;
    }
    check!(tester)(1000);
}
```

Expected result:

```
m2.Check for unicode strings:

Time taken: 2 ms, 420 μs, and 5 hnsecs
1 test(s) run, 0 failed.

OK!
```

Actual result:

```
m2.Check for unicode strings:

    unit_threaded.property.PropertyException@source/m2.d(14): Error calling property function
Invalid UTF sequence: 9bx - Invalid UTF-8 sequence (at index 1)
```

**Comment by atilaneves** [comment]
I'd... also expect valid unicode strings by default. I didn't write that part of the code. This makes sense, but I thin it's going to be hard to do.

**Comment by dhasenan** [comment]
I'll take a look at it later today.

7-bit ASCII should be dead easy: random bytes in the range 1..0x80.

I don't feel like it should be hard to ensure that everything is valid UTF-8 / UTF-16 variable length integer encoding -- generate a series of dchar and convert to the required format.

There are a lot of holes in Unicode, though -- for instance, U+0378 isn't a character, but U+0377 is, as is U+037A. It would be straightforward to generate a few extra characters and filter things through std.uni / std.utf functions.

This would be a usable second pass. A good third pass would be to produce sensible unicode -- combining codepoints disallowed at the start of a string, for instance. Going for broke would be trying to mimic real-world but potentially awkward text (eg a phrase in Arabic in the middle of a Russian sentence).

It wouldn't be bad, or that difficult, to have a dictionary of [naughty strings](https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.txt) included.

Anyway, I'll have a look and maybe pop in with a PR.

**Comment by dhasenan** [comment]
Okay, I figured out what the actual issue with the original code was: it tried to be clever and preemptively convert its character set into the desired string type, then assumed that each code unit was a code point.

So instead of having a `dchar[]` containing the required values, it converted them into `wstring` or `string` or what have you. So you'd have a string with, for instance: `0x61 0x62 0x63 ... 0xC2 0xA1`, where the last two bytes encode ¡ (U+00A1, inverted exclamation mark). The generator would attempt to grab one character at random from that set, and sometimes it would grab `0xC2` and sometimes it would grab `0xA1`, neither of which are valid alone.

This is straightforward to fix and greatly reduces the amount of work I thought I would have to do.
