### ISSUE TITLE
code.dlang.org hasn't picked up 0.7.46

### ISSUE THREAD

**Issue by John-Colvin** [atilaneves/unit-threaded#117]

**Comment by atilaneves** [comment]
That's a code.dlang.org bug. There's nothing different about the 0.7.46 tag.

**Comment by wilzbach** [comment]
Yeah this seems to be a wider issue: https://github.com/dlang/dub-registry/issues/338

**Comment by John-Colvin** [comment]
I was wondering if a manual update would make it work
