### ISSUE TITLE
Choice of gen_ut_main

### ISSUE THREAD

**Issue by russel** [atilaneves/unit-threaded#126]
I have a dub.sdl with:
```
configuration "unittest" {
    targetType "executable"
    targetName "factorial-test"
    preBuildCommands "dub run unit-threaded -c gen_ut_main -- -f ut_main.d"
    mainSourceFile "ut_main.d"
    dependency "unit-threaded" version=">=0.7.49"
}
```
but when I run "dub test"
```
Running custom 'unittest' configuration.
Performing "unittest" build using /usr/bin/dmd for x86_64.
unit-threaded 0.7.49: target for configuration "library" is up to date.
factorial ~master: building configuration "unittest"...
Running pre-build commands...
Building package unit-threaded in /home/users/russel/.dub/packages/unit-threaded-0.7.32/unit-threaded/
Performing "$DFLAGS" build using /usr/bin/dmd for x86_64.
unit-threaded 0.7.32: target for configuration "gen_ut_main" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Running ../../../../.dub/packages/unit-threaded-0.7.32/unit-threaded/gen_ut_main -f ut_main.d
Linking...
```
why is it running ../../../../.dub/packages/unit-threaded-0.7.32/unit-threaded/gen_ut_main instead of ../../../../.dub/packages/unit-threaded-0.7.49/unit-threaded/gen_ut_main?

**Comment by atilaneves** [comment]
Because dub is buggy.

Delete the old version and it'll use the new one.

**Comment by russel** [comment]
Do you know if there is a bug report against Dub for this? If not I'll post one.

**Comment by atilaneves** [comment]
I can't remember if I bothered. I've filed worse issues and they've not even been looked at.

**Comment by russel** [comment]
If you were to post an issue, I'd be happy to rant and turn it into a Big Issue™

**Comment by atilaneves** [comment]
I'd say [this bug](https://github.com/dlang/dub/issues/1217) is a much higher priority.

**Comment by russel** [comment]
I'll join in on that one, but I'll post this problem as a new Dub bug.
