### ISSUE TITLE
Change to subpackages breaks Meson build

### ISSUE THREAD

**Issue by russel** [atilaneves/unit-threaded#127]
The rearrangement into subpackages has (obviously :-) broken the Meson build. I'll take responsibility for updating, no problem. However it may take a little while – I need to understand the new structure, how the Dub build works, and then translate that to the Meson build specification.

Will the new version be 0.8.0 rather than 0.7.50? (Meson versions are a real pain since they do not account for development builds, only release builds :-( so I need to update the number to the next release immediately.).

**Comment by atilaneves** [comment]
If I had my way, I'd change the version to 0.8.0, but due to [this dub bug](https://github.com/dlang/dub/issues/1217) that apparently I'm the only who cares about, I can't.

**Comment by russel** [comment]
I wonder if it is because people use >= rather than == for dependencies?

Matthias has given me an impetus to follow the way the Dub subpackage test builds work rather than the way the release builds work. Normally this would mean a meson.build file for each subpackage, as with Dub files, but I am conscious I am ending up polluting your project. I will try and do it all in the top-level meson.build.

**Comment by atilaneves** [comment]
I always use `~>`. Regardless, any and all incompatibilities between their usage of unit-threaded for testing and a dependent library's, and you can't build. Even though the dependency's version of unit-threaded isn't ever going to be in the build.

Yesterday or the day before I wanted to create a `build` directory and move everything there but I wasn't sure if that would break the meson build.

**Comment by russel** [comment]
Given there is a total restructuring of the project, now would be the time to make any and all changes you want. The Meson build is only there because I asked, it is therefore my problem to make it work!

**Comment by russel** [comment]
Meson seems to work with the meson.build file in the build directory, even though all the documentation says it should be in the project directory. Still getting that linker error though on building get_ut_main. This is very strange, but investigation continues.

**Comment by russel** [comment]
I rearranged the subpackages into alphabetic order to help check the content of the meson.build file, and spontaneously the build works.

**Comment by atilaneves** [comment]
Feel free to issue a PR to close this.

**Comment by russel** [comment]
Pull request #134 submitted.
