### ISSUE TITLE
Allow user to control behaviour for float comparisons

### ISSUE THREAD

**Issue by John-Colvin** [atilaneves/unit-threaded#130]
~~It's~~ `shouldApproxEqual` is very lax by default ~~, plus I might actually care that it gives exactly the same answer.~~

~~Feels like a mine hiding underneath the nice smooth `unit_threaded` API surface. For example, this will pass: `double(int.max).shouldEqual(double(int.max - 21262214)));`, which would be a nasty thing to miss as part of changing a system to use doubles instead of ints.~~

~~Actually, it seems to me that approximate comparison should be opt-in, not opt-out. Currently I opt-out *when I remember* and use plain `assert`~~

**Comment by John-Colvin** [comment]
My bad, I misread the code.

Could `isApproxEqual` and `shouldApproxEqual` be extended to take precision arguments?

**Comment by atilaneves** [comment]
Sure, that makes sense.
