### ISSUE TITLE
How do I use command line parameters?

### ISSUE THREAD

**Issue by steveno** [atilaneves/unit-threaded#137]
I hope this isn't a stupid question, but I'm genuinely stumped. 

When I run `dub test` I want to pass in a command line parameter to a fake config file. I saw in the README about the `-d` command line parameter that must be used with `-s`. I can't just do `dub test -s` though because dub thinks the `-s` is for dub and not for unit-threaded. So where do I put the `-d` or the `-s`?

**Comment by atilaneves** [comment]
Commands like `dub test` and `dub run` pass command-line arguments to the compiled binary by using `--` and adding commands after that.

So either `dub test -- -s` or `dub test -- -d`.

I need to update the README, `-s` and `-d` are now orthogonal.
