### ISSUE TITLE
shouldEqual with objects doesn't check private fields

### ISSUE THREAD

**Issue by unleashy** [atilaneves/unit-threaded#138]
Take the following code:

```d
// in some module...
class A
{
    string foo;
}

// in another separate module...
unittest
{
    auto a = new A;
    auto b = new A;

    a.foo = "1";
    b.foo = "2";

    a.should == b;
}
```

It doesn't pass, thankfully. However, if I change the property `foo` to private:

```diff
+private string foo;
-string foo;
```

It passes, weirdly. If I add an opEquals override:

```d
override bool opEquals(Object b)
{
    return (cast(A) b).foo == foo;
}
```

It still passes! What's going on? I'm using 0.7.54 (latest release at the time of writing).

Thanks!

**Comment by atilaneves** [comment]
> It passes, weirdly.

Not weird at all. If the member is private, unit-threaded can't access it and so can't compare it. It's definitely an anti-pattern to be testing that private members are the same!

> If I add an opEquals override

Ah. That should work.

**Comment by unleashy** [comment]
Thank you!
