### ISSUE TITLE
@ShouldFail tests are treated exactly the same as regular tests

### ISSUE THREAD

**Issue by BenjaminSchaaf** [atilaneves/unit-threaded#14]
When writing something new (especially when using TTD) often its the case that
you have one or more tests which have to pass at some point in the future. Maybe
they are for a separate component, maybe you have multiple tests that rely on
each other and you're working on getting one to pass at a time.

As is the case in `unit-threaded` one would normally mark these tests as
"expected to fail" or "should fail". What I would then expect to happen is that
these tests would run, but would only be reported if the unexpected happened,
ie. they succeeded. Instead they seem to get reported whether they fail or not,
in the same way other tests get reported.

### Tests that fail

```d
@ShouldFail
void testShouldFail() {
    assert(false);
}
```

Report:

```
Test testShouldFail failed.


Time taken: 4 ms, 690 μs, and 6 hnsecs
67 test(s) run, 1 failed, 1 failing as expected.

Unit tests failed!

Error executing command test:
Program exited with code 1
```

### Tests that succeed

Code:

```d
@ShouldFail
void testShouldFail() {
    assert(true);
}
```

Report:

```
Test testShouldFail failed.


Time taken: 4 ms, 356 μs, and 8 hnsecs
67 test(s) run, 1 failed, 1 failing as expected.

Unit tests failed!

Error executing command test:
Program exited with code 1
```

From the documentation in the `README` this doesn't seem like intended
behaviour, but I may be wrong on that front.

**Comment by atilaneves** [comment]
I can reproduce this. It seems to only happen for test functions instead of unittest blocks, for some reason. As a workaround until the fix, use a unittest block. Test functions are now only needed for parameter passing anyway.

**Comment by BenjaminSchaaf** [comment]
This has been fixed for functions without parameters, but is still broken for functions with parameters.
Throwing the following in `tests/pass/attributes` causes the same issue:

```d
@ShouldFail
@(12, 13, 14)
void testValuesShouldFail(int i) {
    (i % 2 == 0).shouldBeFalse;
}
```

It also crashes inside the test suite when reporting because failed tests are searched for by their test name (which does not include the arguments), while test failures are gathered by their name + argument.

**Comment by atilaneves** [comment]
I'm opening a [new issue](https://github.com/atilaneves/unit-threaded/issues/16) for this.
