### ISSUE TITLE
test runner does not run dependencies' unit tests

### ISSUE THREAD

**Issue by joseph-wakeling-frequenz** [atilaneves/unit-threaded#145]
I was adapting an application project to use the `unit-threaded` test runner recently:

```json
    "configurations": [
        {
            "name": "executable"
        },
        {
            "name": "unittest",
            "targetName": "myapp-test-application",
            "targetType": "executable",
            "preBuildCommands": ["dub run unit-threaded -c gen_ut_main -- -f build/ut.d"],
            "mainSourceFile": "build/ut.d",
            "dependencies": {
                "unit-threaded": ">=0.8.0 <0.10.0"
            },
            "dflags": ["-dip25"]
        }
```

... and when running `dub test` I noticed that only modules from the app proper were being mentioned.

To confirm my suspicions I went into a submodule (one of the dub dependencies) and tweaked a unittest there so that it should fail.  Re-running tests, this was not picked up on.  If however I reverted to the regular (non-unit-threaded) test runner, the dependency's unittests were run and the failure triggered.

Is this deliberate?  On the face of it, it seems like a fairly serious bug, as one generally assumes that unittest builds will cover all source code dependencies as well as the main app.

**Comment by joseph-wakeling-frequenz** [comment]
BTW, I did wonder if the `dflags` setting was in some way overriding anything, so I repeated without that present, to the same end.  A unittest in a submodule dependency (included with DUB path dependencies) does not fail when the unit-threaded test runner is used; only unittests in the main app code do.

**Comment by atilaneves** [comment]
This is tricky. As a workaround I'd suggest manually listing the modules to test. I myself don't use the `dub run unit-threaded` trick anymore because dub keeps recompiling the binary and it just takes too long.

**Comment by joseph-wakeling-frequenz** [comment]
Thanks for the suggestion :-)

What do you use instead of `dub run unit-threaded` ... ?  It is what's documented in the README so if there's a better alternative that might be worth updating.

**Comment by atilaneves** [comment]
I write the test file manually to avoid the issues. It's easier now with the `runTestsMain` mixin, so it usually looks like this:

```d
import unit_threaded.runner;
mixin runTestsMain!(
    "pkg.mod1",
    "pkg.mod2",
);
```

I kept the README as it is to make it easy for most people.

**Comment by atilaneves** [comment]
I don't think this will get fixed, and since there's a workaround I'm going to close it.
