### ISSUE TITLE
problem on aarch (android termux)

### ISSUE THREAD

**Issue by ikod** [atilaneves/unit-threaded#161]
Hello,
tried to test my package under android, got:

ldc2 1.13.0
android, termux
$ uname -a
Linux localhost 3.18.71-perf-g43c249b #1 SMP PREEMPT Fri Sep 14 13:20:54 WIB 2018 aarch64 Android

dub test
Running custom 'unittest' configuration.
Performing "unittest" build using /data/data/com.termux/files/usr/bin/ldc2 for aarch64, arm_hardfloat.
automem 0.6.1: target for configuration "library" is up to date.
unit-threaded:from 0.10.3: target for configuration "library" is up to date.
unit-threaded:exception 0.10.3: target for configuration "library" is up to date.
unit-threaded:assertions 0.10.3: target for configuration "library" is up to date.
unit-threaded:integration 0.10.3: target for configuration "library" is up to date.
unit-threaded:mocks 0.10.3: target for configuration "library" is up to date.
unit-threaded:property 0.10.3: building configuration "library"...
../.dub/packages/unit-threaded-0.10.3/unit-threaded/subpackages/property/source/unit_threaded/randomized/benchmark.d(33,38): Warning: skipping definition of function unit_threaded.randomized.benchmark.getQuantilTick!0.75.getQuantilTick due to previous definition for the same mangled name: _D13unit_threaded10randomized9benchmark__T14getQuantilTickVde1PN1ZQyFNaNbNiNfAS4core4time8DurationZQv
/data/data/com.termux/files/usr/bin/ldc2 failed with exit code 1

Thanks for any help!

**Comment by atilaneves** [comment]
Thanks for reporting. I don't however even know how to reproduce this.

**Comment by ikod** [comment]
Hello,
I'll try to investigate and make PR if I'll find fix.

ср, 21 авг. 2019 г., 9:54 Atila Neves notifications@github.com:

**Comment by atilaneves** [comment]
Any updates? I'd rather not have an issue open here for all time otherwise.

**Comment by ikod** [comment]
Hello,
sorry, no updates. I failed to run it on emulator. So It's ok to close issue until real problem.
Thanks!
