### ISSUE TITLE
Unit-Threaded 0.10.4 fails to build with Meson 0.52.0 on Linux

### ISSUE THREAD

**Issue by russel** [atilaneves/unit-threaded#163]
I believe this problem is not a Unit-Threaded problem, I believe it is a Meson regression. I am posting this issue here in case someone other than me comes across the problem.

I have reported this to the Meson folk: https://github.com/mesonbuild/meson/issues/6046

**Comment by michaelbadcrumble** [comment]
Ok @russel did you build it on a Mac?

**Comment by russel** [comment]
No, this is on Linux. I think that is the problem referred to is at the heart of the lack of build. It has now been fixed in Meson Git master but there hasn't been a new release as far as I know.

**Comment by michaelbadcrumble** [comment]
I took a sneak peek in the milestone chart for Meson and looks like version 0.52.1 may release soon.

**Comment by michaelbadcrumble** [comment]
@russel they just released 0.52.1.  Now it’s exclusively the problem on Mac, whatever that maybe.

**Comment by russel** [comment]
@michaelbadcrumble I'll await the updated Debian Sid package of Meson. I no longer have any MacBooks or MacBook Pros, I am an OSX/macOS free zone.

**Comment by michaelbadcrumble** [comment]
I get that, but I was just passing the message that Meson 0.52.1 is available.

**Comment by russel** [comment]
Debian Sid just got Meson 0.52.1. Unit-Threaded seems to build and install fine with this version of Meson.
