### ISSUE TITLE
Command line switches section in the README do not appear to be implemented. 

### ISSUE THREAD

**Issue by sybrandy** [atilaneves/unit-threaded#17]
Not sure if these existed before or if they're planned, but the command line switches that are documented do not appear to be in the 0.6.5 version of the source.

**Comment by atilaneves** [comment]
Which ones?

**Comment by sybrandy** [comment]
I tried -s and -d from from the command line without success.  I also
didn't see them in, IIRC, runtime.d.  I didn't look for it or try it, but I
don't recall seeing -r.

**Comment by atilaneves** [comment]
They're in `options.d`. Are you running the tests with dub? If so, don't forget the `--` to separate unit-threaded's options from dub's, e.g. `dub test -- -s`. Otherwise, I'd have to have access to the exact conditions in order to debug.

**Comment by sybrandy** [comment]
I do run the tests with dub, but I was debugging something so I ran the command directly.  Here's what I ran:

    ../../.dub/packages/unit-threaded-0.6.5/unit-threaded -f bin/ut.d -s -d

And if I do unit-threaded -h, I don't see those options.

**Comment by atilaneves** [comment]
That command won't run the tests; it will just generate the `bin/ut.d` file. `bin/ut.d` is a program that accepts the `-s`, `-d`, and `-h` options. You can run _that_ yourself with rdmd but you'll have to pass it the appropriate `-I` flags and `-unittest` at the very least.

**Comment by sybrandy** [comment]
O.K.  I looked at the dub output and thought that it was the command that
ran the tests.  My mistake.  Thanks.
