### ISSUE TITLE
shouldEqual with epsilon

### ISSUE THREAD

**Issue by WebFreak001** [atilaneves/unit-threaded#170]
There should be an overload in should to allow testing similarity of floats using an epsilon value

like `assert(a == b)` with `epsilon` results in `assert(abs(a - b) < epsilon)`

Otherwise unit-threaded prints cryptic messages such as:
```
openlocationcode.test height in degrees:
    source/openlocationcode.d:836 - Expected: 0.050000
    source/openlocationcode.d:836 -      Got: 0.050000
```

**Comment by atilaneves** [comment]
You should [shouldApproxEqual](https://github.com/atilaneves/unit-threaded/blob/479e205f4dcc34ea42d26d68913bc65f1ecda4ac/subpackages/assertions/source/unit_threaded/assertions.d#L546)

**Comment by atilaneves** [comment]
Which can also be used like this:

```d
  1.0.should ~ 1.0001;
```

**Comment by WebFreak001** [comment]
oh cool, didn't see that in the [dpldocs](https://unit-threaded.dpldocs.info/unit_threaded.assertions.html). I think that symbol needs a ddoc comment to be visible there.

**Comment by atilaneves** [comment]
I added Ddoc in [this commit](https://github.com/atilaneves/unit-threaded/commit/e30958e0d0bb6e1094201f06b90214265710fe84)
