### ISSUE TITLE
`unit_threaded.property.check` bypasses `@safe`

### ISSUE THREAD

**Issue by Geod24** [atilaneves/unit-threaded#176]
Because `check` and relative take an `alias` to a function but are marked as `@trusted`, they essentially pretend to be `@safe` without actually enforcing the `@safe` guarantees.

```D
import unit_threaded.property;

@safe unittest
{
    int* ptr;
    check!((int a) { *(ptr + 256) = 42; return a % 2 == 0; });
}
```

**Comment by atilaneves** [comment]
Oops.
