### ISSUE TITLE
`shouldThrow` & friends are blindly `@trusted`

### ISSUE THREAD

**Issue by Geod24** [atilaneves/unit-threaded#184]
```D
import unit_threaded;

@("Safety test")
@safe unittest
{
    shouldThrow({ int* foo = cast(int*) 42; *foo = 42; });
}
```

This compiles without issue on master.

**Comment by atilaneves** [comment]
`@trusted` is hard.

**Comment by Geod24** [comment]
And `@safe` and `@system` are harder to compose than they should.
At least that would explain the belief that "most D code is `@safe`".

**Comment by atilaneves** [comment]
No, most D code is definitely `@safe`. But it's hard to correctly deal with the issue of catching Throwable *and* dealing with the @safety of user code at the same time.

**Comment by Geod24** [comment]
> No, most D code is definitely `@safe`.

I'm curious, is it just a feeling or is there a metric to back this ? I'll admit that my own position isn't backed by exact numbers, but by:
- The various languages limitations I mentioned (OOP / non templated delegates);
- The projects I've dealt with (DMD, druntime, Vibe.d, dub, other smaller D projects, and pretty much every project on the auto-tester) either didn't have `@safe`, forced `@safe` on the user, or had some overreaching `@trusted`;
- Obviously, my own projects;

If we count in sheer LoCs I'd agree, but simply because trivial statements dominate :)
If you place yourself on a project level (or, let's say, package), then I'm strongly convinced that's not the case. And what's worse, the fact that the core D projects (DMD / druntime) are not (cannot) be `@safe` is a testament to the issue.

> But it's hard to correctly deal with the issue of catching Throwable

Per the spec, that can *never* be `@safe` unless you report and immediately `abort` or similar.
But we know that in practice it works.

> dealing with the `@safe`ty of user code at the same time.

Isn't that a basic requirement for any library though ?
