### ISSUE TITLE
Regression: `unit_threaded.property.check` is `@system` without DIP1000

### ISSUE THREAD

**Issue by Geod24** [atilaneves/unit-threaded#187]
If you make a dub package without `-preview=dip1000` and the following code:
```D
bool func (uint) @safe { return true; }

@("Safety test")
@safe unittest
{
    check!func;
}
```

```console
source/lib.d(26,5): Error: @safe function lib.__unittest_L24_C7 cannot call @system function unit_threaded.property.check!(func, 100).check
../subpackages/property/source/unit_threaded/property.d(21,6):        unit_threaded.property.check!(func, 100).check is declared here
```

Making the template `@safe` reveal the issue:
```console
../subpackages/property/source/unit_threaded/property.d(38,44): Error: cannot take address of local random in @safe function check
../subpackages/property/source/unit_threaded/property.d(67,16): Error: template instance safelyCatchThrowable!(__error, delegate (Throwable t) pure @trusted
{
throw new UnitTestException(text("Property threw. Seed: ", seed, ". Input: ", input(cast(Flag)false), ". Message: ", t.msg), file, line, t);
}
) has no value
source/lib.d(26,5): Error: template instance unit_threaded.property.check!(func, 100) error instantiating
```

**Comment by atilaneves** [comment]
I don't think it's a regression when the code pretended to be @safe before but wasn't. And there's no way for the compiler to guarantee it's @safe without DIP1000. A possible solution is for a @trusted block in there iff DIP1000 isn't used, but... why not compile with DIP1000 instead?

Right now I'm tempted to mark this as "won't fix".

**Comment by Geod24** [comment]
> why not compile with DIP1000 instead?

Well I use Vibe.d

**Comment by atilaneves** [comment]
> > why not compile with DIP1000 instead?
> 
> Well I use Vibe.d

And I assume vibe.d fails to compile with dip1000.... ugh. I'll figure this out.
