### ISSUE TITLE
Missing command line option? (Assumption of using Dub)

### ISSUE THREAD

**Issue by russel** [atilaneves/unit-threaded#200]
When used from Dub, the gen_ut_main executable makes use of the excludedSourceFiles option in the dub.sdl file for the unittest configuration to exclude files from the generated test main. The equivalent exclusion of files capability is not exposed via the command line and so other build tools, e.g. SCons, are not able to exclude files from generation of the test main.

**Comment by atilaneves** [comment]
I would say to not bother using gen_ut_main without dub. In fact, I'm encouraging people to not use it all.

**Comment by russel** [comment]
So is the advice to manually write the main needed, or not to use a build system other than Dub?

**Comment by atilaneves** [comment]
Manually write it. I don't know if it's been fixed, but dub kept rebuilding gen_ut_main every time which added to build times and was driving me nuts.

The thing is, generating a main file with all modules needs to be done by the build system.  I wrote gen_ut_main to do that with dub. Other build systems would have to have their own options.

**Comment by russel** [comment]
If there is a model/template/paradigm manual seems fine. I'll use the generated as guide for now.
Automated is clearly better, but the Dub handling does seem a problem – not for me but generally is.
I'll do a Python script for SCons.

**Comment by atilaneves** [comment]
The template is this;

```d
import unit_threaded;
mixin runTestsMain!(
    "mymodule0",
    "mymodule1",
    // ...
);
```

The only difference from project to project is the exact list of strings with the module names. That's why it's a build system responsibility, since it's the build system that knows which D modules are going to be compiled.

**Comment by russel** [comment]
I guess my current indecision is whether this code should be in the application D code as the test main, or whether it should be a build system provided alternate main. I am finding building the alternate file fairly trivial in SCons, and straightforward(-ish) in Meson.
