### ISSUE TITLE
1.0.1 and 1.0.2 not in code.dlang.org

### ISSUE THREAD

**Issue by russel** [atilaneves/unit-threaded#202]
The latest version of unit-threaded in the Dub repository seems to be 1.0.0, it appears 1.0.1 and 1.0.2 have not made it in.

**Comment by atilaneves** [comment]
That's a dub registry bug, the tags have been pushed.

**Comment by russel** [comment]
OK, thanks.

**Comment by atilaneves** [comment]
I logged into code.dlang.org, tried to do a manual update, the server crashed and rebooted and now the tags seem to be there.
