### ISSUE TITLE
unittests from inside structs aren't discovered

### ISSUE THREAD

**Issue by shishkander** [atilaneves/unit-threaded#21]
See https://github.com/atilaneves/unit-threaded/pull/20

**Comment by shishkander** [comment]
Example of "weirdness" in phobos: https://github.com/dlang/phobos/blob/master/std/format.d#L1169

**Comment by atilaneves** [comment]
Fixed by 13ba2ed9788c707f6d9b1f38998579da8a7baf7f

**Comment by shishkander** [comment]
Thanks for merging + https://github.com/atilaneves/unit-threaded/commit/704c6e01630c0385fde6ffff07217b7c9de9e9c0.
