### ISSUE TITLE
what's this build Error: corrupt MS Coff object module

### ISSUE THREAD

**Issue by mingwugmail** [atilaneves/unit-threaded#213]
I got this error, when build with VisualD-v1.0.1-dmd-2.093.1-ldc2-1.23.0.exe

dmd:

```
lib\unit-threaded_property.lib: Error: corrupt MS Coff object module obj\debug\dummy\dummy\dummy\dummy\dummy\dummy\unit-threaded_property\..\..\..\..\..\..\Users...\AppData\Local\dub\packages\unit-threaded-1.0.4\unit-threaded\subpackages\property\source\unit_threaded\randomized\benchmark.obj 320
lib\unit-threaded_property.lib: Error: corrupt MS Coff object module obj\debug\dummy\dummy\dummy\dummy\dummy\dummy\unit-threaded_property\..\..\..\..\..\..\Users...\AppData\Local\dub\packages\unit-threaded-1.0.4\unit-threaded\subpackages\property\source\unit_threaded\randomized\package.obj 320
Building lib\unit-threaded_property.lib failed!
```

(I didn't add package unit-threaded myself, guess it's indirectly pulled in by some other packages.)

How to fix this Coff object issues?

(BTW, why there are so many \dummy\... dirs?)

**Comment by mingwugmail** [comment]
I just completely deleted that `packages` dir, 

C:\Users...\AppData\Local\dub\packages\<all_the_dirs>

and the <proj_dir>/.dub dir, and also the app.sln file; then I start from scratch:

dub.exe generate visuald

But I got the exact same build error: corrupt MS Coff object.

I think it's showhow caused by the build process itself, maybe just inside the unit-threaded-1.0.4 package, any suggestions where to check further?

**Comment by mingwugmail** [comment]
I just tried, using -m32:

 /mnt/c/project/dlang/dmd-2.093.1/windows/bin/sc.ini
[Environment]
DFLAGS="-I%@P%\..\..\src\phobos" "-I%@P%\..\..\src\druntime\import" "-d" "-m32"

at least that error is gone, and I was able to build:

.dub/lib/unit-threaded_property.lib

So, looks like this unit-threaded_property.lib cannot be build with -m64, but I just wonder why?

**Comment by mingwugmail** [comment]
I think this could be a VisualD issue.  I cannot build with VisualD, but I can build on Windows using command line:

C:\project\dlang\dmd-2.093.1\windows\bin64\dub.exe test --build=unittest

**Comment by mingwugmail** [comment]
for reference: I logged a VisualD issue here

https://issues.dlang.org/show_bug.cgi?id=21194

**Comment by atilaneves** [comment]
I've used VisualD once, 4 years ago. I try as much as possible to never boot into Windows. I have no idea what's happening here nor how it can be related to unit-threaded other than the Windows build was green as of the last merge and I'd be very surprised if it's not green now.
