### ISSUE TITLE
preBuildCommands

### ISSUE THREAD

**Issue by andre2007** [atilaneves/unit-threaded#227]
There is an environment variable SOURCE_FILES. (Unfortunately not documentation yer). I wonder wheter it could be used to simplify the preBuildCommands?

https://github.com/dlang/dub/pull/1817

**Comment by andre2007** [comment]
I am not 100% sure whether `preBuildCommands` in user dub.json is needed at all. A `preGenerateCommands` in your dub package should always be automatically called when user dub package is build.

**Comment by atilaneves** [comment]
What `preBuildCommands`?

**Comment by andre2007** [comment]
The README.md says this preBuildCommand is necessary to use the library in dub projects:

```
 ​"​preBuildCommands​"​: [​"​$DUB run --compiler=$$DC unit-threaded -c gen_ut_main -- -f bin/ut.d -d $DUB​"​],
```

**Comment by atilaneves** [comment]
Ah, that. I haven't used that so long myself that I'd forgotten about it. It seems the dub bug that was preventing me from doing so is now fixed.

Are you suggesting to put a `preGenerateCommands` in unit-threaded itself to always generate the main file for reflection?

I don't understand how `$SOURCE_FILES` helps.

**Comment by andre2007** [comment]
From the README.md it sounds like the whole purpose of gen_ut_main is to find out the modules of the dub package. This information is also located in the mentioned environment variable.

>  Unfortunately, due to the nature of D's compile-time reflection, to use this library a test runner file listing all modules to reflect on must exist. Since this is a tedious task and easily automated, unit-threaded has a dub configuration called gen_ut_main to do just that.

**Comment by andre2007** [comment]
You could give it a try, this would ease the usage of this library.

**Comment by atilaneves** [comment]
I tried using `$SOURCE_FILES` in `preBuildCommands` and `preGenerateCommands` in a different project and dub complained about an invalid variable.

**Comment by andre2007** [comment]
@atilaneves 
Just as explanation: As far as I remember there is a distinction between dub variables and environment variables.
You can not use them everywhere.

But the environment variable definitely exists https://github.com/dlang/dub/blob/79e312d042f66a0ea56879f13c2167bc66d35146/source/dub/generators/generator.d#L830

**Comment by atilaneves** [comment]
I saw the code and the PR. Unfortunately the PR had no tests to accompany it, so I don't know what the diff actually does, if anything.

What I know is that trying to use `$SOURCE_FILES` in the two directives where it'd make sense fails. Where else is it available?

In [the documentation](https://dub.pm/package-format-sdl) it lists `$SOURCE_FILES` in the same column as a few variables that *do* work in those directives. And what precedes that is "Inside of custom command directives".

Right now I don't know how to use `$SOURCE_FILES`. Given it shows up nowhere as an actual variable in the dub git repository I'd guess that nobody else does either.

**Comment by gizmomogwai** [comment]
I just did a quick dub init test project and there
```
preBuildCommands "echo $$SOURCE_FILES"
```
prints the sources of the dub package when building. hope that helps.

**Comment by atilaneves** [comment]
@gizmomogwai Thanks! Weird that it needs to be escaped but other variables don't.
