### ISSUE TITLE
Integrating randomized benchmark and unittest into unit-threaded

### ISSUE THREAD

**Issue by burner** [atilaneves/unit-threaded#24]
so before spending to much time of coding lets think a little. I know crazy.

unit-threaded has the nice feature of also testing function with prefix "test"

my quick(fix->check) benchmarking clone works with functions like

``` D
void theFunctionToTest(Gen!(int, 1, 5) a, Gen!(float, 0.0, 10.0) b)   {
        // This will always be true
        assert(a >= 1 && a <= 5);
        assert(a >= 0.0 && a <= 10.0);

        // super expensive operation
        auto rslt = (a + b);
        doNotOptimizeAway(rslt);

        debug
        {
            assert(rslt > 1.0);
        }
    }
```

Replace theFunctionToTest with testFunctionToTest and we are in business.
Gen!T are structs that have an alias this to T the second and third parameter allow to specify a range. 
Maybe some UDAs would be good to specify how often the function should be tested with random values in the given ranges, but that shouldn't be to hard.
When these functions are used for benchmarking it is necessary that they run singled threaded. The resulting is done in a csv file. I wrote a very small tool that then takes the csv and gnuplot to plot the results.

@atilaneves what do you think?

**Comment by atilaneves** [comment]
The naming convention of "test" is the default, any function can be one with `@UnitTest` on it. There's a problem, though: they need to not take any parameters. Those that do are value-parameterized tests and need to have UDAs with the values to use for each parameter.

Running single-threaded isn't a problem - that's what `@Serial` is for and it could be mandated by the framework for these functions.

The other thing is while benchmarking is important, I was thinking more of a Hasklell quickcheck property based testing framework.

**Comment by burner** [comment]
If currently, all test functions are without parameter, it think it feels natural that all test functions with parameters are quickcheck test functions.

I see your point about quickcheck. The quickcheck part is that we run the function with different values for the parameters. Calling the function multiple times and with different parameters will be done by unit-threaded. 

Putting the assertions in a debug block allows the test function to be used for benchmarks. So IMO that is not really a limitation, as I assume unittesting is done in debug mode and benchmarking is done in release mode.

**Comment by atilaneves** [comment]
I didn't explain myself well: functions with parameters are currently value-parameterized tests. That wouldn't play well with the quickcheck stuff without horribly complicating the implementation of the reflection code. But... we can say that functions that start with "the" or another prefix instead are quickcheck functions. Or an UDA to distinguish. I don't know. We could look at the types and if they're `Gen` as well, but that's the complication I was talking about in the code.

I'm not sure I get the last two paragraphs.

**Comment by burner** [comment]
I like the UDA and prefix variant. Testing for Gen could lead to problems with there are none.

**Comment by burner** [comment]
https://github.com/burner/unit-threaded/tree/quickcheck branch quickcheck

**Comment by burner** [comment]
I'm not sure right now how to get the tests picked up by unit-threaded. Any points are welcome

**Comment by atilaneves** [comment]
The tests for unit-threaded itself are run by dub as it would for any "regular" project. They're not being picked up because the code you added isn't in source/unit-threaded. Looking at `dub.json` I'm not even sure how dub knows to compile the "real" source code! I moved the randomized package and [created a PR](https://github.com/burner/unit-threaded/pull/1).

**Comment by burner** [comment]
thanks

**Comment by atilaneves** [comment]
Taking a look today and playing with the code that's in the quickcheck branch. If I understand correctly this is just the basics to start generating random values of certain types, correct? Then a layer on top to allow for property based testing would have to be written.

**Comment by russel** [comment]
Just to note that a property-based framework needs to do automated random selection of values from the domain based on type signature, and to do shrinking in the case of failure.

**Comment by burner** [comment]
I thought about shrinking. The problem is it only really works with single argument functions, otherwise you don't know which variable to bisect.

**Comment by atilaneves** [comment]
Next step? Merge as is and take it from there?

**Comment by burner** [comment]
Fair question. As you properly have seen it is up for review and comments for phobos inclusion. Lately I didn't really had time to work in the integration into uni-threaded. The only thing left to do IMO is to find the prefixed or annotated functions and call the benchmark function on them. The search part was something I did struggle with, because I'm new to the codebase and for time reasons.
If you wouldn't mind doing that, I would be grateful. What I will do, is extending the plotting tool. It is totally sufficient, but I have some cool ideas for it.

Thoughts?

**Comment by atilaneves** [comment]
I'll see what I can do on the search front, then I'll look into how to do shrinking and all that good stuff

**Comment by burner** [comment]
shrinking is nice for single parameter pure functions. Everything else, not so much IMO.

**Comment by burner** [comment]
https://github.com/atilaneves/unit-threaded/pull/30
