### ISSUE TITLE
template instance GetTypes!uint does not match template declaration GetTypes(alias T)

### ISSUE THREAD

**Issue by nmtigor** [atilaneves/unit-threaded#26]
Hello, 

I have a file mymed/color.d:

    module mymed.color;
    alias RGB = uint;

When I run dub test, it outputs following errors:

Running ../../../../home/nmtigor/.dub/packages/unit-threaded-0.6.16/unit-threaded/unit-threaded -f bin/ut.d
../../../../home/nmtigor/.dub/packages/unit-threaded-0.6.16/unit-threaded/source/unit_threaded/reflection.d(316,27): Error: template instance GetTypes!uint does not match template declaration GetTypes(alias T)
../../../../home/nmtigor/.dub/packages/unit-threaded-0.6.16/unit-threaded/source/unit_threaded/reflection.d(260,45): Error: template instance unit_threaded.reflection.moduleTestFunctions!(color).moduleTestFunctions.pred!(color, "RGB") error instantiating

Is it a bug? When I set version to "==0.6.4", it works fine.

**Comment by atilaneves** [comment]
Looks like a bug, I'll take a look.
