### ISSUE TITLE
shouldEqual for objects with doubles does not behave like shouldEqual on doubles

### ISSUE THREAD

**Issue by gizmomogwai** [atilaneves/unit-threaded#28]
``` d
unittest {
  import unit_threaded;
  struct TestStruct {
    double x;
  }
  1.0.shouldEqual(1.0001);
  TestStruct(1.0).shouldEqual(TestStruct(1.0001));
}
```

**Comment by atilaneves** [comment]
I don't know how I've missed this for 12 days: I'll take a look.

**Comment by atilaneves** [comment]
A workaround is to define opEquals for the struct. Other than that I'd be wary of trying to be too clever with aggreagates. Arguably a solution is to not approximate for doubles.
