### ISSUE TITLE
cartesianProduct involving finite ranges...

### ISSUE THREAD

**Issue by magicl** [atilaneves/unit-threaded#31]
I am trying to move from another unit-testing lib to yours, but am getting this problem.

(also had a problem with a module that was called config, classing with std.getopt.config, but that was solved by renaming my module)

Can you help me explain what is going on here, and how to work around?

/usr/include/dmd/phobos/std/algorithm/setops.d(119,10): Error: static assert  "cartesianProduct involving finite ranges must have at least one finite forward range"
../../.dub/packages/unit-threaded-0.6.22/unit-threaded/source/unit_threaded/reflection.d-mixin-381(381,29):        instantiated from here: cartesianProduct!(void[], void[])
../../.dub/packages/unit-threaded-0.6.22/unit-threaded/source/unit_threaded/reflection.d(445,25):        instantiated from here: createTestData!(test, "testHeader")
../../.dub/packages/unit-threaded-0.6.22/unit-threaded/source/unit_threaded/reflection.d(341,12):        instantiated from here: moduleTestData!(test, isTestFunction, createFuncTestData)

**Comment by atilaneves** [comment]
Without seeing your code I can't know for sure, but it seems that you have a function that possibly begins with the word `test` that is screwing up the compile-time reflection. You can add `@DontTest` to the offending function as a workaround, but I can't fix this generically without seeing the function itself.

**Comment by magicl** [comment]
Is there a way to make the reflection-code more robust so that it checks for the requirements for e.g. cartesianProduct up-front, and gives an error message if the requirements are not met? I'll keep digging into this when I have a chance.

**Comment by magicl** [comment]
I had a function called testSomething, taking two parameters, but of course not using your @Value attributes.. Would be great if your lib could detect this and send a warning

**Comment by atilaneves** [comment]
You don't need `@Values` for non-unittest functions, the library assumes it's supposed to be a test if it's in camelCase and begins with `test`. I agree that detecting it and either a pragma warning or disconsidering it is a good idea, but I can't do that unless I know why it doesn't compile. I need the smallest reproducing code you can muster.

**Comment by magicl** [comment]
Here is the code. Each of the two test functions generate their own issue. This should of course have been fixed by adding @Values or by saying @DontTest, but this might not be obvious when someone tries to add unit-threaded to an existing program.

```
module app;

import std.stdio;

version(unittest) {
}
 else {
void main()
{
	writeln("Edit source/app.d to start your project.");
}
 }
 void testFoo(int i) {
  writeln("foo");
}

void testHeader(string mod, string testName) {
  writeln("****************** Test: " ~ mod ~ " - " ~ testName ~ " ******************");
}
```

I get this error:
Running custom 'unittest' configuration.
Performing "unittest" build using dmd for x86_64.
unit-threaded 0.6.23: target for configuration "library" is up to date.
utfail ~master: building configuration "unittest"...
Running pre-build commands...
Building package unit-threaded in /home/oivind/.dub/packages/unit-threaded-0.6.22/unit-threaded/
Performing "debug" build using dmd for x86_64.
unit-threaded 0.6.22: target for configuration "gen_ut_main" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Running ../../.dub/packages/unit-threaded-0.6.22/unit-threaded/unit-threaded -f bin/ut.d

../../.dub/packages/unit-threaded-0.6.23/unit-threaded/source/unit_threaded/reflection.d(377,79): Error: template unit_threaded.reflection.createTestData!(app, "testFoo").createFuncTestData.map!((a) => tuple(a)).map cannot deduce function from argument types !()(void[]), candidates are:
/usr/include/dmd/phobos/std/algorithm/iteration.d(450,10):        unit_threaded.reflection.createTestData!(app, "testFoo").createFuncTestData.map!((a) => tuple(a)).map(Range)(Range r) if (isInputRange!(Unqual!Range))
../../.dub/packages/unit-threaded-0.6.23/unit-threaded/source/unit_threaded/reflection.d(444,25): Error: template instance unit_threaded.reflection.createTestData!(app, "testFoo") error instantiating
../../.dub/packages/unit-threaded-0.6.23/unit-threaded/source/unit_threaded/reflection.d(340,12):        instantiated from here: moduleTestData!(app, isTestFunction, createFuncTestData)
../../.dub/packages/unit-threaded-0.6.23/unit-threaded/source/unit_threaded/reflection.d-mixin-62(62,1):        instantiated from here: moduleTestFunctions!(app)
../../.dub/packages/unit-threaded-0.6.23/unit-threaded/source/unit_threaded/reflection.d(70,12):        instantiated from here: allTestsWithFunc!("moduleTestFunctions", app)
../../.dub/packages/unit-threaded-0.6.23/unit-threaded/source/unit_threaded/reflection.d-mixin-51(51,8):        ... (1 instantiations, -v to show) ...
../../.dub/packages/unit-threaded-0.6.23/unit-threaded/source/unit_threaded/runner.d(46,27):        instantiated from here: allTestData!"app"
bin/ut.d(10,12):        instantiated from here: runTests!"app"
/usr/include/dmd/phobos/std/algorithm/setops.d(119,10): Error: static assert  "cartesianProduct involving finite ranges must have at least one finite forward range"
../../.dub/packages/unit-threaded-0.6.23/unit-threaded/source/unit_threaded/reflection.d-mixin-380(380,29):        instantiated from here: cartesianProduct!(void[], void[])
../../.dub/packages/unit-threaded-0.6.23/unit-threaded/source/unit_threaded/reflection.d(444,25):        instantiated from here: createTestData!(app, "testHeader")
../../.dub/packages/unit-threaded-0.6.23/unit-threaded/source/unit_threaded/reflection.d(340,12):        instantiated from here: moduleTestData!(app, isTestFunction, createFuncTestData)
../../.dub/packages/unit-threaded-0.6.23/unit-threaded/source/unit_threaded/reflection.d-mixin-62(62,1):        ... (3 instantiations, -v to show) ...
../../.dub/packages/unit-threaded-0.6.23/unit-threaded/source/unit_threaded/runner.d(46,27):        instantiated from here: allTestData!"app"
bin/ut.d(10,12):        instantiated from here: runTests!"app"
