### ISSUE TITLE
stderr output should not be hidden by default

### ISSUE THREAD

**Issue by CyberShadow** [atilaneves/unit-threaded#311]
It's now been several occasions where I've jumped into debugging someone else's D project, and to get an understanding of things, added some `stderr.writeln`s. And, every time, I step into the same rake: the output doesn't appear, I spend half an hour debugging why the code is (apparently!) not running at all, and finally realizing, "Oh, this project is using that stupid `unit-threaded` library", and replace `stderr` with `File("/dev/tty", "wb")` which thankfully still works.

I know there's a switch to turn on debug output. However, 1) "printf debugging" is a universal concept, and taking it away from developers who are jumping in to hack on your project is, IMHO, a most unlucky idea; 2) the `unit-threaded` invocation might be buried deep into the project's test scripts, so even given the knowledge that the project is using `unit-threaded` and what switch needs to be added, it's still work to be done just to get back a basic debugging tool.

I don't use `unit-threaded` myself, But, I've now ran into this problem both when contributing to others' open-source projects, and at work.

I understand that the rationale is "tests run in parallel, so the output might be interleaved". I think that's a poor argument, because hiding the output completely is undeniably and entirely worse than having it interleave. I can fix interleaved output using universal tools such as `taskset`, which are going to work with any test harness or programming language, and don't require me to stop what I'm doing and read the particular test harness's documentation.

Possible solutions:

1. Don't redirect `stderr` by default. Instead, tests should follow the UNIX rule of silence and only print stuff on request or as extra information before a test failure.
2. Redirect it to a temporary buffer or file, and print it if the test fails. I think that's what tools like `ninja` do.
3. Detect when `stderr` has been written to, and print a message that instructs users how to see the output. The instructions should work even if the invocation is not directly editable, e.g. it could be an environment variable, or `cat`-ing a file, but shouldn't be a command-line switch or a function that needs to be called in the code.

Thanks!

**Comment by atilaneves** [comment]
"hiding the output completely is undeniably and entirely worse than having it interleave" - I wholeheartedly disagree. However, since the first version of unit-threaded I've figured out a way to not interleave output (as long as people use `writeln` instead of calling printf directly) and have been thinking of not disabling output for a while now.

**Comment by CyberShadow** [comment]
> I wholeheartedly disagree

I am curious to hear your arguments! The only one I can think of is aesthetics.

**Comment by atilaneves** [comment]
> > I wholeheartedly disagree
> 
> I am curious to hear your arguments! The only one I can think of is aesthetics.

That, and making sense what's been printed!
