### ISSUE TITLE
gdc: error: unrecognized command-line option ‘-preview=dip1000’; did you mean ‘-fpreview=dip1000’?

### ISSUE THREAD

**Issue by mw66** [atilaneves/unit-threaded#314]
Hi, I'm trying to build unit-threaded/2.2.0, using gdc:

```
$ gdc --version
gdc (GCC) 14.1.0
```

got an error:

```
gdc: error: unrecognized command-line option ‘-preview=dip1000’; did you mean ‘-fpreview=dip1000’?

```

How to fix this? or any other version that does not use this flag?

Thanks.

**Comment by mw66** [comment]
found this:

https://gcc.gnu.org/onlinedocs/gcc-14.1.0/gdc.pdf

looks like GDC's flag called `fpreview` instead of `preview`.

**Comment by atilaneves** [comment]
You could make the flags dependent on the compiler in the dub recipe. Feel free to submit a PR.
