### ISSUE TITLE
remove public import from unit_threaded.should

### ISSUE THREAD

**Issue by linkrope** [atilaneves/unit-threaded#35]
The `public import unit_threaded.attrs;` seems to be unused.
Moreover, it makes it harder to reuse `unit_threaded.should`.
(I'm trying to support the "should assertions" in [dunit](https://github.com/linkrope/dunit).)

**Comment by atilaneves** [comment]
If not for that, it wouldn't be possible to just `import unit_threaded` and then use the attributes therein. How does it make reusing `unit_threaded.should` harder?

**Comment by linkrope** [comment]
When I import `dunit` as well as `unit_threaded.should`, I get the following error:

    Error: dunit.framework.UnitTest() at src/dunit/framework.d(765,7) conflicts with unit_threaded.attrs.UnitTest at ../../../.dub/packages/unit-threaded-0.6.27/unit-threaded/source/unit_threaded/attrs.d(5,1)

dunit's `UnitTest` mixin conflicts with unit-threaded's `UnitTest` attribute, even if I only want to reuse the fluent assertions.

A remedy could be to move the `public import unit_threaded.attrs;` from source/unit_threaded/should.d to the other public imports in source/unit_threaded/package.d.

At least, unit-threaded's `dub test` is still successful after the change.

**Comment by atilaneves** [comment]
I seem to have missed this last comment. Just use the fully qualified name for the attribute.

**Comment by linkrope** [comment]
My problem is that I want to get rid of this selective import:
https://github.com/linkrope/dunit/blob/master/fluent_assertions.d#L9

In my opinion, the public import of `unit_threaded.attrs` in `unit_threaded.should` is in the wrong place. The right place for this public import would be `package.d`.

Or is there any situation where you have import `unit_threaded.should` without importing `unit_threaded`?

**Comment by atilaneves** [comment]
Ah. I had that public import there before `package.d` was even a feature! You're right of course, and I'll move it where it belongs.
