### ISSUE TITLE
setup/shutdown for multiple tests

### ISSUE THREAD

**Issue by jacob-carlborg** [atilaneves/unit-threaded#37]
As far as I can see, setup/shutdown only works for TestCase, which only supports a single test. Is that something that could be improved, either to allow setup/shutdown for global functions/unittests or allow multiple tests in a single TestCase? Ideally both 😃.

**Comment by atilaneves** [comment]
There's only already CompositeTestCase for multiple tests, even if right now AFAIK it's only used internally. I haven't needed setup or shutdown for tests for years, which is why I haven't worked on the support. I've been moving away from it so tests are self-sufficient and therefore easier to read. Things can definitely be improved if you want that functionality. Could you list your requirements please? Thanks.

**Comment by jacob-carlborg** [comment]
> There's only already CompositeTestCase for multiple tests, even if right now AFAIK it's only used internally

Aha, I'll take look.

> Could you list your requirements please? 

For my requirements I would need:

* Support for multiple tests in TestCase
* Having setup/shutdown run for each test in the TestCase

For consistent I would also expect:

* Support for setup/shutdown for `unittest` blocks and unit test functions as free functions

**Comment by atilaneves** [comment]
For multiple tests I really need an example of what you would like to write. I understand that it's multiple tests, but I'm having difficulties picturing how it'd look; usually I implement what I'd want to use and in this case I'd be scratching an itch I just don't have.

You could always use child classes: they'd all inherit setup and shutdown.

As for unittest blocks: I could add UDAs for that but it's not less typing:

```d
@Setup!func unittest { ... }
```

vs

```d
unittest {
    auto dependency = func();
}
```

**Comment by jacob-carlborg** [comment]
> For multiple tests I really need an example of what you would like to write. I understand that it's multiple tests, but I'm having difficulties picturing how it'd look; usually I implement what I'd want to use and in this case I'd be scratching an itch I just don't have.

I'm trying to come up with a good example that's quite short. I know that I'm using it in Ruby and I'm trying to do more things in D instead of Ruby and I feel that I need this functionality. Here's an example of where I use it in Ruby [1]. I'm suppressing printing output and reading of a file. It's execute before each of the seven tests. It might not be needed for all of them, but I don't really care because I always want to suppress these method calls.

Here's an example of how it might be used in D:

```d
class FooTest : TestCase
{
    A a;
    B b;
    Foo foo;

    void setup()
    {
        a = new A();
        b = new B();
        foo = new Foo();
    }

    void testProcess1()
    {
        foo.process1(a, b).shouldBeTrue();
    }

    void testProcess2()
    {
        foo.process2(a, b).shouldBeTrue();
    }
}
```

Here I would expect that each test, prefixed with `test`, would be run on a new instance of `FooTest`. That would automatically cleanup the sate that is set as instance variables. `setup` would be run before each test is run on the new instance.

I think it more clearly separates the state/data setup and the actually test. I think that `unit-threaded` looks like the best alternative in D and I would like to avoid creating my own test framework.

> As for unittest blocks: I could add UDAs for that but it's not less typing:

I was more thinking:

```d
module foo;

void setup() { ... }

unittest { }
unittest { }
```

`setup` is automatically run before executing each of the unit tests, for this given module.

[1] https://github.com/jacob-carlborg/tm_grammar/blob/dev/spec/application_spec.rb#L8-L11

**Comment by jacob-carlborg** [comment]
Thanks.
