### ISSUE TITLE
Windows: Symbol Undefined _mkdtemp

### ISSUE THREAD

**Issue by dazoe** [atilaneves/unit-threaded#38]
Building on windows gave me Symbol Undefined _mkdtemp.
I worked around this by replacing

```
extern(C) char* mkdtemp(char*);
```

with

```
version(Windows) {
    extern(C) int mkdir(char*);
    extern(C) char* mktemp(char*);
    char* mkdtemp(char* t) {
        char* result = mktemp(t);
        if (result is null) return null;
        if (mkdir(result)) return null;
        return result;
    }
} else {
    extern(C) char* mkdtemp(char*);
}
```

Then I was presented with

```
unit_threaded.should.UnitTestException@source\unit_threaded\integration.d(173): Expected: ["foo", "toto"]
     Got: ["foo\r", "toto"]
```

After much digging I found out that the test file is being created with File.writeln which uses  LockingTextWriter which uses fputc which on windows changes \n to \r\n.

I can think of 2 solutions to this
1. change shouldEqualLines to strip \r
2. change how the test file is being created.

I think option 1 would be the better solution.

**Comment by dazoe** [comment]
Simple fix for shouldEqualLines is to use splitLines instead of split("\n")

**Comment by atilaneves** [comment]
I don't run Windows so it'll be hard for me to verify the fix works. Could you please roll the `splitLines` change and the first one you posted in a pull request please? Thanks!
