### ISSUE TITLE
A few extra should...

### ISSUE THREAD

**Issue by SerialVelocity** [atilaneves/unit-threaded#4]
Hey,

Would it be possible to add:
  shouldNotBeEmpty, shouldBeEmpty, shouldHaveSize, shouldBeBiggerThan, shouldBeSmallerThan for arrays and associative arrays?

Thanks,
Nebster

**Comment by SerialVelocity** [comment]
I can create a PR for this if you don't have time but it will probably be a while before I get around to it.

**Comment by atilaneves** [comment]
What would `shouldHaveSize` (I'd name it `shouldHaveLength`) bring?

     [1, 2, 3, 4].length.shouldEqual(4);

I can see a `shouldBeGreaterThan` though, but for numbers (then use `.length`).

**Comment by SerialVelocity** [comment]
Yes, sorry that makes sense. I just wanted to throw that idea out while I was at work so I didn't think it through thoroughly.

**Comment by SerialVelocity** [comment]
Why are there both ```should``` and ```check``` btw?

**Comment by atilaneves** [comment]
The `check` functions came first, then I switched to `should` but didn't want to break any existing code. As for why the new ones come in two versions as well, that was for consistency.

**Comment by SerialVelocity** [comment]
It may be worth deprecating the old ones and moving all the code over to ```should```. Then you keep it around for a few major versions (making new ones only ```should```) and then finally remove them.
