### ISSUE TITLE
Command line switch to unhide stdout/stderr

### ISSUE THREAD

**Issue by Abscissa** [atilaneves/unit-threaded#47]
Would be very helpful while debugging. Even if it only works in --single mode. Without that, I have to switch to D's built-in test runner to do any writeln debugging..

**Comment by atilaneves** [comment]
You can use `writelnUt` instead

**Comment by Abscissa** [comment]
`writelnUt` isn't outputting anything for me.

**Comment by Abscissa** [comment]
Also, using `writelnUt` means adding a bunch of

```d
version(Have_unit_threaded) {} else
	alias writelnUt = writeln;
```

if I want to retain the ability to switch back to the built-in test runner via a dub configuration.

**Comment by atilaneves** [comment]
I thought you meant in a unittest, that's what `writelnUt` is for. For some reason I also forgot to tell you about the `-d` switch. That's what stops redirecting stdout. It implies `-s` since otherwise the output would interweave.

**Comment by Abscissa** [comment]
On 10/04/2016 01:35 PM, Atila Neves wrote:
> I thought you meant in a unittest, that's what `writelnUt` is for. For some reason I also forgot to tell you about the `-d` switch. That's what stops redirecting stdout. It implies `-s` since otherwise the output would interweave.
>

Well I did mean inside unittests (as well as elsewhere while debugging), 
but `-d` does what I need, thanks.

**Comment by russel** [comment]
Is -d a compile-time or run-time option?

**Comment by russel** [comment]
Definitely run time option.
