### ISSUE TITLE
Readme.md sample configuration missing targetType for dub

### ISSUE THREAD

**Issue by Dechcaudron** [atilaneves/unit-threaded#48]
Going to give unit-threaded a try (looks awesome by the way, great job on it and thanks a lot beforehand). Unfortunately, as stupid as it might seem, I spent well over 10 minutes trying to understand why I was getting this error:

`Source file '<projectDir>/bin/ut.d' not found in any import path.`

Thing is, I basically copy-pasted the README.md's dub sample configuration. It doesn't produce any errors, but neither does it seem to generate "bin/ut.d". The source of the problem is the lack of the "targetType" option for the "unittest" configuration.

Fastest fix ever, I guess. Just adding one line. Or maybe I missed on something, did I?

"targetType" : "executable" does the trick, of course.

**Comment by atilaneves** [comment]
I think maybe I assumed that the project would add `"targetType": "executable"`, I can't remember. Thanks for filing the bug, I'll sort it out.

**Comment by Dechcaudron** [comment]
Thank you for the library :)

**Comment by atilaneves** [comment]
Thanks for the interest!
