### ISSUE TITLE
Mock fails if the mocked object imports something

### ISSUE THREAD

**Issue by belka-ew** [atilaneves/unit-threaded#51]
I have a problem if the mocked function's parameters type or return type is imported from a different module.

Here is a short example:

**example/example_pass.d:**
```d
import unit_threaded.runner;

import tests.pass.mock;

int main(string[] args) {
    return args.runTests!(
        tests.pass.mock,
    );
}
```
**tests/pass/types.d:**
```d
module tests.pass.types;

struct A
{
}
```
**tests/pass/mock.d:**
```d
module tests.pass.mock;

import tests.pass.types;
import unit_threaded;

@safe pure unittest {
    interface Foo {
        A foo() @safe pure;
    }

    A fun(Foo f) {
        return f.foo();
    }

    auto m = mock!Foo;
    m.expect!"foo";
    fun(m);
}
```

I'm getting the following output:
> Running custom 'unittest' configuration.
> Performing "unittest" build using dmd for x86_64.
> unit-threaded 0.7.2+commit.30.g0b01cd2: building configuration "unittest"...
> Warning: testIssue31 passes the criteria for a value-parameterized test function but doesn't have the appropriate value UDAs.
>          Consider changing its name or annotating it with @DontTest
> source/unit_threaded/mock.d-mixin-156(156,5): Error: undefined identifier 'A'
> source/unit_threaded/mock.d-mixin-156(158,12): Error: undefined identifier 'A'
> source/unit_threaded/mock.d(173,14): Error: template instance unit_threaded.mock.Mock!(Foo, "tests.pass.mock") error instantiating
> tests/pass/mock.d(15,14):        instantiated from here: mock!(Foo, "tests.pass.mock")
> dmd failed with exit code 1.

I've found a workaround. If I make "tests.pass.types" to a public import, then it compiles, but it doesn't seem to be supposed to work this way.

**Comment by atilaneves** [comment]
It's ugly, but I can't see how else to fix it. Change the mock line to this and it'll work now:

```d
auto m = mock!(Foo, __MODULE__, "tests.pass.types");
```
