### ISSUE TITLE
Strange output behavior

### ISSUE THREAD

**Issue by gizmomogwai** [atilaneves/unit-threaded#53]
Hi ...

I am developing a small library (read only git access) that behaves strange when running its unit-tests.
Most of the time, I do not get output, but sometimes, my debug output appears. I always run the tests with the same random seed (please see snippet ...).
Could it be me, that is somehow corrupting the state of the unit-test flags?

~/D/D/_/_/g/dgit on(master) is(dirty) ➜  dub test -- --seed 0                                                                                                                   538ms
Running custom 'unittest' configuration.
Performing "unittest" build using dmd for x86_64.
unit-threaded 0.7.4: target for configuration "library" is up to date.
dgit 1.0.0: target for configuration "unittest" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Running ./dgit --seed 0

Automatically generated file gen/ut.d
Running unit tests from dirs ["."]
dgit.consumeSourceLength:
dgit.consumeSourceOffset:
dgit.consumeTypeAndSizeHeader:
dgit.decodeDeltaEncoding:
dgit.deltaDecodingOfPack:
dgit.offsetVarint:
dgit.varint:
dgit.visitors.FileVisitor:
dgit.visitors.FileVisitor.files:
asciitable.unittest0:
dgit.binarysearch indexOf:
dgit.visitors.StatusVisitor:
dgit.visitors.ShowVisitor:

Time taken: 58 ms, 926 μs, and 4 hnsecs
13 test(s) run, 0 failed.

OK!

~/D/D/_/_/g/dgit on(master) is(dirty) ➜  dub test -- --seed 0                                                                                                                   428ms
Running custom 'unittest' configuration.
Performing "unittest" build using dmd for x86_64.
unit-threaded 0.7.4: target for configuration "library" is up to date.
dgit 1.0.0: target for configuration "unittest" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Running ./dgit --seed 0

Automatically generated file gen/ut.d
Running unit tests from dirs ["."]
.git/objects/pack/pack-634357003a90cc0709ec11c5ec4cdc2e148969bb.idx mmap first bytes: [255, 116, 79, 99, 0, 0, 0, 2, 0, 0]
objectNames: ["00b6ad768cfc3a30a9c557ca26860dd0a088ea41", "05c1fa5802071e0b24201ea42a9c7e9fff85f196", "0b896c9ed2455599fd6af093d87bae3156ec6b0a", "1364647013992cc48477a9ca9065986e51807cab", "164f484cf0c8ed53293c3536ab4707634218accb", "246d0192bb436de9083c2337b33675f37a5d76c5", "29a6887eb108d2010bd9ffb8c87dba99f2c60295", "2a9d81d80b3c39f4f06e1cfdc172e2b0451210a8", "2d3dcc530037db93799a30efa60fc89214adbd1a", "39cdcd4822c7250fb5f1b39828e24fb62695d2ea", "3d34e56be5cf5e673c915751215839467ccbd2f5", "406afcad7a542845477d538fd68ea2a9aeb24ba0", "40e01c1ca691ea7920b07a6ab3aabeb701a65984", "49664b855e876af6a482d704867cd1240ab05b5b", "4a484b5fd9ddfeefac0f87077ec1300ae42221c6", "4ead87a7b634a19acbaa4f05ade917a2e8f7eba1", "554dc72fca945090a05e683279b6cb929819b7b7", "55f2dc979a49e58eb1c55e199dcb1b2e1365d5fc", "5bf7deff7399a4e6157c059cdf044adf155b7817", "61671a996989bbbddf6379175a1a3e502badcaf0", "704dae6df39317abb7408621caf837b639b943a5", "741c34f28661dd004cb132731ceef42ae9ae766d", "8d53596808f83aea639a89f40ffb97232a334fcb", "8e65723f4a475773a1010c7ac332f0a66a5340d1", "92efd5f67dcd642ccce8259fc9d38b84f64419d1", "9332dcfdaf2d2f5ed947e7e5599a111c91ec2f51", "9b5a37e48e57f64d85485211e7f096a1ee399539", "9b804e2b947a95d368ad3a5bac1012a39fe571e0", "9c19fd02e8f4191ef8be2b89f0af3474cad26dce", "a151256d55cb393acb8343cf91f235129ed5a56a", "a2559ff27f8c85334ef0dbe55b5a49630dd0d485", "a715a4b6cee5316fdc67019ca6f23452b24c9d4d", "ab0ab0893920c8afd8b12bcc802ac1f342126b89", "af661f0382f28fb2762b317b87ed2e204321a9e9", "ba22483dbf2d18edf7518f04faf2ff5bfe5c19fc", "ce39a9ebbdac39ac513b9f6bbd0bdcf3eedfee66", "ce80dba8059ecb0c813de537ddda36922c51a6fe", "d392c64bb6201d5146a19522d6fc9b812ec839a9", "d7193e77aed2f36610e2f9c9eeeb002da65e827a", "dad64bbf4045d87285850105683324d774040ed2", "dbc0eaf384fd24bb0bd4a2c41229e49069158bc0", "df69fc33409c177a86f891a83829d5fd932f8626", "ec624fe85a0a4113f01f6cb69356092b19591387", "eec6d03821141160d0439c896de1e431c192718e", "f58f05ab34bf945d658647b288839ed352a71db6", "f7322f49878e1b67908a4533f618a850d5e9c8ce", "f91c825a5dec0161042b02e53bed5c2b0f10815c"]47
asciitable.unittest0:
dgit.binarysearch indexOf:
dgit.consumeSourceLength:
dgit.consumeSourceOffset:
dgit.consumeTypeAndSizeHeader:
dgit.decodeDeltaEncoding:
dgit.deltaDecodingOfPack:
dgit.varint:
dgit.visitors.FileVisitor:
dgit.offsetVarint:
dgit.visitors.FileVisitor.files:
dgit.visitors.ShowVisitor:
dgit.visitors.StatusVisitor:

Time taken: 60 ms, 256 μs, and 1 hnsec
13 test(s) run, 0 failed.

OK!

~/D/D/_/_/g/dgit on(master) is(dirty) ➜  dub test -- --seed 0                                                                                                                   342ms
Running custom 'unittest' configuration.
Performing "unittest" build using dmd for x86_64.
unit-threaded 0.7.4: target for configuration "library" is up to date.
dgit 1.0.0: target for configuration "unittest" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Running ./dgit --seed 0

Automatically generated file gen/ut.d
Running unit tests from dirs ["."]
.git/objects/pack/pack-634357003a90cc0709ec11c5ec4cdc2e148969bb.idx mmap first bytes: [255, 116, 79, 99, 0, 0, 0, 2, 0, 0]
objectNames: ["00b6ad768cfc3a30a9c557ca26860dd0a088ea41", "05c1fa5802071e0b24201ea42a9c7e9fff85f196", "0b896c9ed2455599fd6af093d87bae3156ec6b0a", "1364647013992cc48477a9ca9065986e51807cab", "164f484cf0c8ed53293c3536ab4707634218accb", "246d0192bb436de9083c2337b33675f37a5d76c5", "29a6887eb108d2010bd9ffb8c87dba99f2c60295", "2a9d81d80b3c39f4f06e1cfdc172e2b0451210a8", "2d3dcc530037db93799a30efa60fc89214adbd1a", "39cdcd4822c7250fb5f1b39828e24fb62695d2ea", "3d34e56be5cf5e673c915751215839467ccbd2f5", "406afcad7a542845477d538fd68ea2a9aeb24ba0", "40e01c1ca691ea7920b07a6ab3aabeb701a65984", "49664b855e876af6a482d704867cd1240ab05b5b", "4a484b5fd9ddfeefac0f87077ec1300ae42221c6", "4ead87a7b634a19acbaa4f05ade917a2e8f7eba1", "554dc72fca945090a05e683279b6cb929819b7b7", "55f2dc979a49e58eb1c55e199dcb1b2e1365d5fc", "5bf7deff7399a4e6157c059cdf044adf155b7817", "61671a996989bbbddf6379175a1a3e502badcaf0", "704dae6df39317abb7408621caf837b639b943a5", "741c34f28661dd004cb132731ceef42ae9ae766d", "8d53596808f83aea639a89f40ffb97232a334fcb", "8e65723f4a475773a1010c7ac332f0a66a5340d1", "92efd5f67dcd642ccce8259fc9d38b84f64419d1", "9332dcfdaf2d2f5ed947e7e5599a111c91ec2f51", "9b5a37e48e57f64d85485211e7f096a1ee399539", "9b804e2b947a95d368ad3a5bac1012a39fe571e0", "9c19fd02e8f4191ef8be2b89f0af3474cad26dce", "a151256d55cb393acb8343cf91f235129ed5a56a", "a2559ff27f8c85334ef0dbe55b5a49630dd0d485", "a715a4b6cee5316fdc67019ca6f23452b24c9d4d", "ab0ab0893920c8afd8b12bcc802ac1f342126b89", "af661f0382f28fb2762b317b87ed2e204321a9e9", "ba22483dbf2d18edf7518f04faf2ff5bfe5c19fc", "ce39a9ebbdac39ac513b9f6bbd0bdcf3eedfee66", "ce80dba8059ecb0c813de537ddda36922c51a6fe", "d392c64bb6201d5146a19522d6fc9b812ec839a9", "d7193e77aed2f36610e2f9c9eeeb002da65e827a", "dad64bbf4045d87285850105683324d774040ed2", "dbc0eaf384fd24bb0bd4a2c41229e49069158bc0", "df69fc33409c177a86f891a83829d5fd932f8626", "ec624fe85a0a4113f01f6cb69356092b19591387", "eec6d03821141160d0439c896de1e431c192718e", "f58f05ab34bf945d658647b288839ed352a71db6", "f7322f49878e1b67908a4533f618a850d5e9c8ce", "f91c825a5dec0161042b02e53bed5c2b0f10815c"]47

**Comment by atilaneves** [comment]
Which library? If I can't reproduce it I can't debug it.

**Comment by gizmomogwai** [comment]
You are totally right, the only question is, if you heard something like this before?
I will close for know, as the code is in no state to be shared. Thanks!

**Comment by atilaneves** [comment]
No, I've never seen anything like that before.
