### ISSUE TITLE
Emit Failures as one-liners with file and line numbers.

### ISSUE THREAD

**Issue by Cody-Duncan** [atilaneves/unit-threaded#58]
**Current output (single threaded mode):**
basic_tests.Failure Test:
    source\basic_tests.d:12 - unittest failure
basic_tests.Failure Test Dos:
    source\basic_tests.d:18 - unittest failure
basic_tests.Sum Test:
Test "basic_tests.Failure Test" failed.
Test "basic_tests.Failure Test Dos" failed.

**Request Output:**
Test "basic_tests.Sum Test" succeeded;
Test "basic_tests.Failure Test" failed; source\basic_tests.d:12 - unittest failure
Test "basic_tests.Failure Test Dos" failed; source\basic_tests.d:18 - unittest failure

**Rationale:**
- Multi-threaded unit tests can interleave the test names and exception printouts. This makes it difficult to tie failure reason/file/line ("source\basic_tests.d:18 - unittest failure") to the name of the test it failed on. Forced to use single-threaded mode to guarantee that information is on the following line.
- The test printout at the end does not specify the reason the test failed.

By having the results on one-line, at the end, with file and line number, it avoids interleaving the printout and simplifies writing regular expressions to detect these failures in the output.

**Comment by atilaneves** [comment]
I've thought about this and am still not sure.

**Comment by atilaneves** [comment]
I'm going to close this for now. Feel free to submit a PR.
