### ISSUE TITLE
Sometimes unit tests in a package.d file don't get picked up

### ISSUE THREAD

**Issue by atilaneves** [atilaneves/unit-threaded#61]

**Comment by radcapricorn** [comment]
...and sometimes having a package.d leads to import errors. I.e. with a project
```
src/
    sub/
        folder/
            package.d
```
unit-threaded attempts to import module sub.folder.folder, which does not exist.

**Comment by atilaneves** [comment]
Do you have an isolated example?

**Comment by radcapricorn** [comment]
You can grab a small test directory structure [here](https://www.dropbox.com/s/a5gjr00rsf7r9h9/utfail.zip?dl=0).
This yields
~/.dub/packages/unit-threaded-0.7.24/unit-threaded/source/unit_threaded/reflection.d-mixin-133(133,8): Error: module memory is in file 'ext/memory/memory.d' which cannot be read
