### ISSUE TITLE
How to use unit-threaded from SCons or Meson?

### ISSUE THREAD

**Issue by russel** [atilaneves/unit-threaded#62]
Currently instructions say how to use unit-threaded with Dub – using JSON syntax, should add examples with SDLang suntax as well. It should be possible to use unit-threaded in SCons and Meson builds. In the short term this would be how to use Dub to get the package and run things explicitly from the command line. This can then be transformed into "plugins" to SCons and Meson to get dependencies from the Dub repository using the API. I guess CMake should be added to the mix as well.

I am happy to do the SCons version of this first as a trial to then see how to do it is Meson and possibly CMake.

**Comment by atilaneves** [comment]
I'll update the example to show SDL as well. I'd just never used SDL myself before, but I do now at work.
I've never gotten CMake to work properly with D and the last time I tried was last week. Nor had I heard it was even possible to build D with SCons and Meson. Having written a build system myself I don't have too much interest in this. My main issues are getting `__traits(getUnittests)` to actually work in builds that don't compile everything at once and how slow the compile-time features are.

**Comment by russel** [comment]
I need to try and get the CMake working with D for use with CLion, for mixed C++ and D codes. Meson I prefer to CMake and am using it in some places for D, it works well where all dependencies are handled by the platform, ditto SCons. (I think I am still the de facto maintainer of the D support in SCons.) SCons (without the D tool) can do "all at once" builds, Meson and CMake cannot. Having got my factorial project building with Dub, I can play further now myself, to try and extract a rule for SCons, which I think is a good first step.

**Comment by atilaneves** [comment]
I think this a special case of the general problem "how to build dub packages without using dub as a build system", so I'll close it. For CMake, SCons or Meson it's as simple as adding `-I` to the `source` directory in this repo and compiling all the source files in there. The easiest is to use reggae since there's nothing to be done.
