### ISSUE TITLE
Using the runTests template

### ISSUE THREAD

**Issue by russel** [atilaneves/unit-threaded#64]
The gen_ut_main script writes a ut_main.d which appears to assume:

a) Dub is being used.
b) The Dub documentation is wrong and "all at once" is the default not "file at a time" as the documentation appears to claim.
c) The ut_main.d file is created in the project directory.
d) The source is in a directory source.

I am trying to get unit-threaded working from SCons (and Meson but that will have to wait pending working out how to do all source at once compiling). For a project with everything at the top level I have everything working (but you need an extra directory (SConsDub) that I haven't made public as yet) see https://github.com/russel/Factorial/tree/master/D.

For a project with a source and test-source structure, it seems impossible to get ut_main.d to compile with the SCons way of building. The project is at https://github.com/russel/ApproxGC, also needs the as yet unpublished SConsDub. I have failed to get Dub to be able to build the integration tests (the application and unittest buildwork fine), which may indicate either a problem with my understanding of Dub, or of unit-threaded. Or both.

For the work Dub unitests the ut_main.d file is:
```
//main
//Automatically generated by unit_threaded.gen_ut_main, do not edit by hand.
import std.stdio;
import unit_threaded;

int main(string[] args)
{
    writeln("\nAutomatically generated file ut_main.d");
    writeln(`Running unit tests from dirs ["."]`);
    return runTests!(
                     "main"
                     )
                     (args);
}
```
which indicates the `runTests` template assumes all the files are in the source directory. Compare this though to the "no structure" project:
```
//factorial
//Automatically generated by unit_threaded.gen_ut_main, do not edit by hand.
import std.stdio;
import unit_threaded;

int main(string[] args)
{
    writeln("\nAutomatically generated file ut_main.d");
    writeln(`Running unit tests from dirs ["."]`);
    return runTests!(
                     "factorial"
                     )
                     (args);
}
`` the file is in . not source. So the `runTests` template must have a search path. Trying to build the ApproxGC integrationtests with Dub, I get:
```
|> dub test --config=integrationtest
Generating test runner configuration 'approx-gc-test-integrationtest' for 'integrationtest' (executable).
Excluding main source file ut_main.d from test.
Source file '/home/users/russel/Repositories/Git/Masters/ApproxGC_D/test-source/main.d' not found in any import path.
```
I guess I need to fix this Dub build before progressing the SCons work further.

**Comment by atilaneves** [comment]
> a) Dub is being used.

Correct. It's a helper script for the general use case. Basically dub knows where the source files are, so it'd be silly to write code to figure that out. Unless it's your use case...

> b) The Dub documentation is wrong and "all at once" is the default not "file at a time" as the documentation appears to claim.

Is this documentation in unit-threaded?

> c) The ut_main.d file is created in the project directory.

Not necessarily. The `-f` option takes a file name, it can be output to anywhere.

> d) The source is in a directory source.

That's because dub assumes that.

The easiest way forward here is to write an SCons script that produces the `ut_main.d` file. The current way of doing things is indeed attached to dub, as using dub as the build system means adding code generation there. To add support for SCons or Meson then those build systems would have to use their information about where the source is and how it's laid out  in order to be able to auto-generate the main file.

**Comment by russel** [comment]
I think the only thing that is a Unit_Threaded thing is possibly b) all the others are other places. I'll see if I can find the location, if it is Unit_Threaded I'll send in a pull request.

I wrote a Python function in SCons to replace use of Dub to create ut_main.d. The code to run the algorithm is smaller than the code to run Dub. :-)
