### ISSUE TITLE
Are release and unittests builds different?

### ISSUE THREAD

**Issue by russel** [atilaneves/unit-threaded#65]
When using Dub, there is a build of unit-threaded for each build type, which is not unreasonable per se. But is there a difference between the release and unittest build of unit-threaded for a given build? Is there a reason not to use a release build of unit-threaded for running tests?

**Comment by atilaneves** [comment]
I've never used/tried the release build. One problem that comes to mind is that the asserts would be turned off. Of course this isn't a problem when using the custom assertions. I don't know why one would want a release build of unit-threaded. Runtime performance of testing code hasn't been a concern so far.

**Comment by russel** [comment]
Good point! I clearly wasn't thinking properly. However when I try:
```
dub build --build=unittest --compiler=ldc2
```
I get a raft of error. These do not happen when building unit-threaded via a "dub test " of an application so that must use a different dub command line to build unit-threaded.

**Comment by russel** [comment]
It seems that the hash at the end of the directory name for the builds in the .dub/builds directory is going to be quite crucial since it is different for different build drivers, i.e. using SCons or manual command line I am getting a different directory name.

**Comment by atilaneves** [comment]
`dub test` is a bit special, I wouldn't be surprised if you got different results with `dub build --build=unittest`

**Comment by russel** [comment]
`dub build --build=unittest` fails to build, lots of compilation errors. For the SCons stuff I am using `dub build` and just using the debug build.

**Comment by atilaneves** [comment]
I think this is a dub issue, so closing. Feel free to disagree and then I'll reopen it.

**Comment by russel** [comment]
I agree this is a Dub thing. I will ask in their "help space" when I get a problem with the SCons builds.
