### ISSUE TITLE
Mocking a class - returnValue!("func")

### ISSUE THREAD

**Issue by grogancolin** [atilaneves/unit-threaded#68]
When mocking a classes return value, mock!"" fails with something like the following:
```
../../.dub/packages/unit-threaded-0.7.22/unit-threaded/source/unit_threaded/mock.d-mixin-199(199,1): Error: undefined identifier 'vmnames_0_returnValues'
../../.dub/packages/unit-threaded-0.7.22/unit-threaded/source/unit_threaded/mock.d(182,41): Error: template instance unit_threaded.mock.Mock!(Hyp).Mock.returnValue!(0, "vmnames", string[]) error instantiating
source/model.d(348,32):        instantiated from here: returnValue!("vmnames", string[])
```

The class looks something like:
```
class Hyp{
    this(){} // this is also required for mocking a class
    string[] vmnames(){
        // return array of vmnames
         .....
    }
}
```

If I create an interface to model the Hyp object, and mock using that, it all works swimmingly.

**Comment by atilaneves** [comment]
This might take until next week to fix since I'm at DConf.

**Comment by grogancolin** [comment]
https://github.com/atilaneves/unit-threaded/compare/master...grogancolin:cgrogan/test_class_mock#diff-0eecdf5aa5e9e0259e3b4582ebcdcc34R304

**Comment by atilaneves** [comment]
I realised why your example doesn't work: unit-threaded doesn't support mocking non-abstract functions. I have a fix, but it only works with non-const non-immutable member functions. Does that work for you?

**Comment by grogancolin** [comment]
It would work yes for my use case. 

I was looking into it a little and it seems (as far as I can tell at least) that it should be doable to override everything except final functions. 
Which is a slight limitation of this scheme. 

I'm thinking I might rewrite my code to provide an interface I can mock against.

But to answer your question - that fix/improvement would work for me!

Thanks for looking into it.

**Comment by atilaneves** [comment]
It should be possible to override any non-`final` function, yes, and that's what my branch does right now. It's just that supporting `const` and `immutable` functions is a lot more work, so I'll push what I have now.

**Comment by grogancolin** [comment]
Excellent! 

Thank you.
