### ISSUE TITLE
Test function naming problem

### ISSUE THREAD

**Issue by russel** [atilaneves/unit-threaded#77]
Using the @Values(…)/@("name")unitest{…} structure seems to work fine for me, however I think this means I really want test functions. I find that @(…)void testFlobadob(…){…} seems to work fine. BUT only if the name is NOT test_flobadob. As soon as I introduce the _ to the function name it appears that the function is no longer recognised as a test function.

**Comment by atilaneves** [comment]
The algorithm is that it begins with the word `test` then an upper-case character. If you want any other function to be considered a test, you can add the `@UnitTest` UDA to it.
