### ISSUE TITLE
Integration with vibe.d

### ISSUE THREAD

**Issue by Amaranthos** [atilaneves/unit-threaded#78]
Hi there,

I'm curious as to whether unit-threaded is intended to be able to be used with a vibe project.
I've run into issues where running the unit-threaded tests (with `dub test -- -s`) causes the tests to seemingly run forever.

dub.sdl:
```
targetType "executable"
dependency "vibe-d" version="~>0.7.32"

configuration "executable" {
}

configuration "unittest" {
	dependency "unit-threaded" version="~>0.7.24"
	mainSourceFile "bin/ut.d"
	preBuildCommands "dub run unit-threaded -c gen_ut_main -- -f bin/ut.d"
}
```

rest.api.d:
```d
module blogd.rest.restapi;

import blogd.rest.irestapi;
import blogd.data.models.post;

class RestApi : IRestApi {
	this() {

	}

	Post[] queryPosts() @safe {
		return [];
	}

	Post queryPosts(long id) @safe {
		return Post.init;
	}
}

@("GET /posts should return all posts")
unittest {
	import vibe.vibe;

	auto router = new URLRouter;
	//router.registerRestInterface(new RestApi);

	auto res = createTestHTTPServerResponse();
	auto req = createTestHTTPServerRequest(URL("http://localhost/posts"));
	//router.handleRequest(req, res);
	//std.stdio.writeln("Hello");
}
```

Un-commenting any of the lines in the unittest block can cause this to happen, however running it as is lets the tests run and outputs the report.

**Comment by atilaneves** [comment]
I've ran into this issue and filed a bug in vibe.d. It appears that it doesn't like threads hanging around. I _might_ have fixed this in unit-threaded in master. I don't know because I don't remember which of my projects used to fail due to vibe.d.

A solution that will work regardless is to run any vibe.d projects's unit tests with `--single`. But try `~master` first.

**Comment by Amaranthos** [comment]
I'm already running in single-threaded and against release 0.7.24. 

The vibe issue for reference:
https://github.com/rejectedsoftware/vibe.d/issues/1657

**Comment by atilaneves** [comment]
You can also try `versions unitUnthreaded` in your `dub.sdl` or `versions: ["unitUnthreaded"]` in `dub.json`. That makes it so no threads are even started. I've also had to do that for certain projects.

**Comment by Amaranthos** [comment]
Ok cool, confirmed work around adding `versions "unitUnthreaded"` into the "unittest" configuration  in your dub.sdl.

Hopefully the threading issue can be resolved with vibe.d soon.
