### ISSUE TITLE
isEqual ignores fields in base class

### ISSUE THREAD

**Issue by linkrope** [atilaneves/unit-threaded#82]
It's wrong that the following unit test passes:

    class A
    {
        string x;

        override string toString() const
        {
            return x;
        }
    }

    class B : A
    {
    }

    unittest
    {
        import unit_threaded;

        auto actual = new B;
        auto expected = new B;

        actual.x = "foo";
        expected.x = "bar";
        actual.shouldEqual(expected);
    }

The reason is that `.tupleof` returns a tuple "of all the fields in the class, excluding [...] the fields in the base class".

BTW: the `static assert` that `toString` is overriden is leftover from a previous implementation?

**Comment by atilaneves** [comment]
No idea about the `static assert`. I agree the test above shouldn't pass. The fix is not going to be fun...

**Comment by linkrope** [comment]
`actual..shouldEqual(expected)` should pass for objects iff `actual == expected` is `true`, shouldn't it?

I suggest to use a different function name (like `shouldBeEquivalent`) for the comparison of data fields.

See also: https://buildplease.com/pages/testing-deep-equalilty/

**Comment by atilaneves** [comment]
I'm not a fan of `shouldBeEquivalent` - what's the use of comparing references? If anything there should be a `shouldBeSameReference`, but I'm still not sure what use that would be.

**Comment by linkrope** [comment]
But `actual == expected` compares references only if `opEquals` is not overridden. If `opEquals` is overridden, then it should be used by `shouldEqual`. Imagine there is some kind of cache data field that is to be ignored.

**Comment by MWumpusZ** [comment]
Purely from the meaning of the name, an operation called `shouldEqual`(s) surely ought to use `opEquals`?

Beyond the naming, the `opEquals` comparison is surely what we usually want when checking equality in unit tests?  Occasionally we may want to insisting on `is`-equality.

I can't see a case where we want to check equality using introspection on the attributes of the objects in question - that information should be none of our business, as users of the object.

**Comment by atilaneves** [comment]
@MWumpusZ Yes, I think you and @linkrope are right.
