### ISSUE TITLE
Defining ctor in TestCase derived class makes it to be non test case.

### ISSUE THREAD

**Issue by drug007** [atilaneves/unit-threaded#83]
```
class TestWithCtor : Testcase
{
    // this() {}

   override test() {}
}
```
if uncomment the line above `unit-threaded` doesn't think `TestWithCtor` is test anymore. I'd like to have const member in my test, but I cannot initialize them in `setup`, ctor is needed.

**Comment by atilaneves** [comment]
BTW, you don't need to derive from `unit_threaded.testcase.TestCase`.

**Comment by drug007** [comment]
Thank you!. But I failed to avoid deriving from `TestCase` in my case. What did you mean exactly?

**Comment by atilaneves** [comment]
I don't really use test classes at all, I've only kept them for backward compatibility. Looking at my own examples they all seem to derive from `TestCase` so maybe I'm actually wrong! The ones in unit-threaded's own unit tests don't, that's what made me think that.

**Comment by drug007** [comment]
I see. I use test class just because they have been used already. May be I'll change it, but now let it be. Thank you again for your work.
