### ISSUE TITLE
Failed compilation if test file module property doesn't match directory structure

### ISSUE THREAD

**Issue by mattremmel** [atilaneves/unit-threaded#84]
How to reproduce:

```
project:
foo/
    dub.json
    source/
        app.d
        bar.d
```
bar.d:
____
```
module foo.bar;

int adder(int x, int y) { return x + y }


@("adder test")
unittest {
    int n = adder(4, 4);
    assert(n == 8);
}
```
____

$ dub test
[.. skipping startup output ..]
Running ../../.dub/packages/unit-threaded-0.7.28/unit-threaded/gen_ut_main -f bin/ut.d
../../.dub/packages/unit-threaded-0.7.28/unit-threaded/source/unit_threaded/reflection.d-mixin-53(53,18): Error: module foo.test from file source/bar.d must be imported with 'import foo.bar;'
../../.dub/packages/unit-threaded-0.7.28/unit-threaded/source/unit_threaded/runner.d(41,27): Error: template instance unit_threaded.reflection.allTestData!"bar" error instantiating
bin/ut.d(7,16):        instantiated from here: runTests!"test"
dmd failed with exit code 1.
____
If I change the module of bar.d to "module bar;", or I move bar.d into a folder called "foo"(source/foo/bar.d) then it will compile and run just fine. It seems to be a problem when there is an extra module symbol at the beginning of the module that isn't present on the filesystem. The reason I ran into this is because I'm using 'source' as my root source directory, but wanted the project name to be at the beginning of all the module names, so when its imported in another project it makes sense where its coming from (import myproject.foo.bar). I'd prefer not to nest all my source files inside of another folder inside source (source/myproject/foo/bar.d) if possible.

Hope this makes sense, if not I'd be happy to provide a zip of the test project.

**Comment by Extrawurst** [comment]
Actually if you want to refer to module `bar` as being in package `foo` then it needs to be placed into a folder `foo`. see https://dlang.org/spec/module.html

```
The Identifiers preceding the rightmost are the Packages that the module is in. The packages correspond to directory names in the source file path
```

**Comment by mattremmel** [comment]
I see that now. Typically thats how I lay them out, although in this case and other times the very first module identifier will be the project name, even though its not actually corresponded to a matching directory, and its always compiled. The only issues I've run into with it has been unit-threaded, but maybe thats fair since what I'm doing isn't technically compliant with the spec. I'm happy to change my directory names, I just thought maybe this was unwanted behavior. Since dub doesn't complain about it, it took me a while to track the problem down, and I'm sure I won't be the only one at some point. If this is too hard to address, I'm happy to close this as a none issue. It would just be a nicety.

**Comment by atilaneves** [comment]
This isn't a problem with unit-threaded as a library - it's the generator for the main file that's failing. Unfortunately, that'd be extremely hard to fix. I suggest either using the expected directory structure or writing out your main file manually with the module names as you want them.

**Comment by atilaneves** [comment]
Thanks for the kind words!

I've had many, many problems with modules when the module name doesn't match the directory structure. Sometimes to the point of things not compiling depending on _how_ they're compiled. It's not worth the hassle.
