### ISSUE TITLE
unit_threaded.mock.MockImplCommon.expect is marked as @safe and pure, while it should not be

### ISSUE THREAD

**Issue by ghost91-** [atilaneves/unit-threaded#86]
The function `unit_threaded.mock.MockImplCommon.expect` is marked both `@safe` and `pure`:
```D
void expect(string funcName, V...)(auto ref V values) @safe pure {
    import std.conv: to;
    import std.typecons: tuple;

    expectedFuncs ~= funcName;
    static if(V.length > 0)
        expectedValues ~= tuple(values).to!string;
    else
        expectedValues ~= "";
}
```
This should not be the case, because one of the `values` might overload `toString` in a way that is not `@safe` or `pure`. An example where this is the case, is the Bson type of vibe.d. In this case, `toString` is not `pure`.

However, removing `@safe` and `pure` from the `expect` function is no loss at all, because it is a template function, and so the atributes will be inferred anyways.

**Comment by atilaneves** [comment]
Thanks for filing the issue. As you mention, this is a function template and shouldn't have had attributes on it explicitly. I guess I forgot to remove them after debugging an issue.
