### ISSUE TITLE
Segmentation fault, if shouldEqual argument is null

### ISSUE THREAD

**Issue by linkrope** [atilaneves/unit-threaded#88]
unittest
    {
        class C {
            int foo;
            override string toString() @safe pure nothrow const { return null; }
        }

        C c = null;
        c.shouldEqual(c);
    }

The problem is

    return value.tupleof == expected.tupleof;

**Comment by linkrope** [comment]
With the "fix", there is still a segmentation fault if only one of the arguments is `null`.
Fix should have been something like:

    if (value is null || expected is null)
        return value is null && expected is null;
    return value.tupleof == expected.tupleof;

**Comment by atilaneves** [comment]
I'm not sure that that's a real fix - if you want to write a test that says an object is `null`, use `shouldBeNull`. If you pass in `null` for expected, which the test controls, it probably should segfault.

**Comment by linkrope** [comment]
You mean:

    assert(expected !is null);
    return value !is null && value.tupleof == expected.tupleof;

But, what if a range of objects is expected:

    actual.shouldEqual([c, null, c]);

Currently, this is no problem because of issue #89.
