### ISSUE TITLE
isEqual specialization for objects is not used for object ranges

### ISSUE THREAD

**Issue by linkrope** [atilaneves/unit-threaded#89]
This means, that `actual.shouldEqual(expected)` could pass while `[actual].shouldEqual([expected])` fails.

**Comment by atilaneves** [comment]
Example?

**Comment by linkrope** [comment]
unittest
    {
        class C {
            override string toString() @safe pure nothrow const { return null; }
        }
    
        auto actual = new C;
        auto expected = new C;
    
        actual.shouldEqual(expected);  // passes: actual.tupleof == expected.tupleof
        [actual].shouldEqual([expected]);  // fails: actual != expected
    }

By the way: the example would have been easier with `new Object`.
But `shouldEquals` requires `toString` to be `const`,  which `Object.toString` isn't.
Is it a bug or a feature, that `shouldEqual` can only be used with objects that override `toString`?

**Comment by atilaneves** [comment]
`Object.toString` should probably be `const`, I think it isn't due to history alone. As for requiring `toString`, I guess a bug? Arguably it should use `std.conv.to!string`.

**Comment by linkrope** [comment]
[Object not const correct](https://issues.dlang.org/show_bug.cgi?id=1824) was reported in 2008.

`convertToString` already tries `value.to!string`: 
https://github.com/atilaneves/unit-threaded/blob/master/source/unit_threaded/should.d#L629

Casting `const` away would help: `(cast(Object) value).toString`

**Comment by atilaneves** [comment]
Thanks for the good work, I also addresses non-`const` `toString`.

**Comment by linkrope** [comment]
Sorry, but there are two more things:

1. The `zip` in `isEqual` causes some UTF-8 decoding, so that `['\xff'].shouldEqual(['\xff'])` fails now.
2. The `pure` in `convertToString` is the reason why `shouldEqual(new Object, new Object)` still does not compile.

**Comment by atilaneves** [comment]
That `pure` was left by mistake.

**Comment by atilaneves** [comment]
As for UTF-8 decoding... argh phobos.
