### ISSUE TITLE
move structs used by the mockStruct functions to module level

### ISSUE THREAD

**Issue by ghost91-** [atilaneves/unit-threaded#90]
Would it be possible to move the ths structs used by the mockStruct functions to the module level? Currently they are nested inside the functions. I'd like this to happen, because it would allow me to inject those mocks with a dependency injection framework ([poodinis](https://github.com/mbierlee/poodinis)). On the other hand I understand that those structs should probably not be used directly, so nesting them seems like a good idea. What do you think about this?

**Comment by atilaneves** [comment]
If you need the struct's type and not its name you should be able to use `ReturnType!mockStruct`.

**Comment by atilaneves** [comment]
@ghost91- Do you still need this?

**Comment by ghost91-** [comment]
No, I don‘t.
