### ISSUE TITLE
Cannot test dub subpackages

### ISSUE THREAD

**Issue by rjframe** [atilaneves/unit-threaded#91]
I have the following dub.json utilizing two subpackages, one of which uses unit-threaded as the test runner:

```
{
    "name": "base",
    "targetType": "none",
    "dependencies": {
        "base:subone": "*",
        "base:subtwo": "*"
    },
    "subPackages": [
        {
            "name": "subone",
            "sourcePaths": ["subone/source"],
            "configurations": [
                {
                    "name": "executable",
                    "targetType": "executable"
                },
                {
                    "name": "unittest",
                    "targetType": "executable",
                    "preBuildCommands": [
                        "dub run unit-threaded -c gen_ut_main -- -f bin/ut.d"
                    ],
                    "mainSourceFile": "bin/ut.d",
                    "excludedSourceFiles": ["subone/source/app.d"],
                    "dependencies": {
                        "unit-threaded": "~>0.7.31"
                    }
                }
            ]
        },
        {
            "name": "subtwo",
            "targetType": "executable",
            "sourcePaths": ["subtwo/source"],
        }
    ]
}
```
When executing `dub test base:subone` I receive the message:

```
unit-threaded 0.7.31: building configuration "gen_ut_main"...
Linking...
Running ..\..\AppData\Roaming\dub\packages\unit-threaded-0.7.31\unit-threaded\gen_ut_main.exe -f bin/ut.d
Error: Could not execute dub describe -c unittest:
stdout:

stderr:
Unknown build configuration: unittest
```
`dub describe -c  unittest` defaults to the base package, which doesn't work; unit-threaded should be executing `dub describe -c unittest base:subone`.

**Comment by atilaneves** [comment]
The workaround here is to write `ut.d` by hand. Another one (not sure it'd work) would be to have a global unittest configuration, and not for just one subpackage.

I'm not sure how I'd fix this - it'd involve knowing about subpackages, which dub doesn't tell you about. The library would have to read a `dub.json` _or_ a `dub.sdl` and parse it to find out. This would be a lot of work for what I'd consider an edge case.

**Comment by rjframe** [comment]
Splitting subpackages into their own dub.json files and using a custom `ut.d` works; I just `cd` to the subpackage's directory and `dub test`.

Thanks.
